/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view.forms;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;

/**
 *
 * @author Mr OLOGIZ
 */
public class FrmDodavanjeNalogaUTermin extends javax.swing.JDialog {

    /**
     * Creates new form FrmDodavanjeNalogaUTermin
     */
    public FrmDodavanjeNalogaUTermin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        panelTermini = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTermini = new javax.swing.JTable();
        lblDatumTermina = new javax.swing.JLabel();
        txtDatumTermina = new javax.swing.JTextField();
        lblVremeKrajaTermina = new javax.swing.JLabel();
        txtKrajTermina = new javax.swing.JTextField();
        lblVremePocetkaTermina = new javax.swing.JLabel();
        lblVremeKrajaTermina1 = new javax.swing.JLabel();
        txtPocetakTermina = new javax.swing.JTextField();
        txtTrajanjee = new javax.swing.JTextField();
        panelNaloziClanova = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNaloziClanova = new javax.swing.JTable();
        btnDodajNalogUTabelu = new javax.swing.JToggleButton();
        btnOmoguciDodavanjeViseNaloga = new javax.swing.JToggleButton();
        panelPrisustvoTerminu2 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblPrisustvaa = new javax.swing.JTable();
        btnDodajNalogUTermin = new javax.swing.JToggleButton();
        lblError = new javax.swing.JLabel();
        panelNaloziClanovaDodati = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblNaloziClanovaZaDodavanje = new javax.swing.JTable();
        btnDodajNalogeUTermin = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelBackground.setBackground(new java.awt.Color(0, 0, 0));

        panelTermini.setBackground(new java.awt.Color(0, 0, 0));
        panelTermini.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Termini", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        tblTermini.setBackground(new java.awt.Color(0, 0, 0));
        tblTermini.setFont(new java.awt.Font("Microsoft YaHei", 0, 11)); // NOI18N
        tblTermini.setForeground(new java.awt.Color(255, 255, 255));
        tblTermini.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTermini.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(tblTermini);

        lblDatumTermina.setBackground(new java.awt.Color(0, 0, 0));
        lblDatumTermina.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblDatumTermina.setForeground(new java.awt.Color(255, 255, 255));
        lblDatumTermina.setText("Datum termina (yyyy-mm-dd):");

        txtDatumTermina.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        txtDatumTermina.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        lblVremeKrajaTermina.setBackground(new java.awt.Color(0, 0, 0));
        lblVremeKrajaTermina.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblVremeKrajaTermina.setForeground(new java.awt.Color(255, 255, 255));
        lblVremeKrajaTermina.setText("Vreme kraja termina:");

        txtKrajTermina.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        txtKrajTermina.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        lblVremePocetkaTermina.setBackground(new java.awt.Color(0, 0, 0));
        lblVremePocetkaTermina.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblVremePocetkaTermina.setForeground(new java.awt.Color(255, 255, 255));
        lblVremePocetkaTermina.setText("Vreme početka termina:");

        lblVremeKrajaTermina1.setBackground(new java.awt.Color(0, 0, 0));
        lblVremeKrajaTermina1.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblVremeKrajaTermina1.setForeground(new java.awt.Color(255, 255, 255));
        lblVremeKrajaTermina1.setText("Trajanje:");

        txtPocetakTermina.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        txtPocetakTermina.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        txtTrajanjee.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        txtTrajanjee.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout panelTerminiLayout = new javax.swing.GroupLayout(panelTermini);
        panelTermini.setLayout(panelTerminiLayout);
        panelTerminiLayout.setHorizontalGroup(
            panelTerminiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTerminiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTerminiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDatumTermina)
                    .addComponent(lblVremeKrajaTermina))
                .addGap(18, 18, 18)
                .addGroup(panelTerminiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKrajTermina, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatumTermina, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(panelTerminiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVremePocetkaTermina)
                    .addComponent(lblVremeKrajaTermina1))
                .addGap(28, 28, 28)
                .addGroup(panelTerminiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTrajanjee, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPocetakTermina, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelTerminiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelTerminiLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1081, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelTerminiLayout.setVerticalGroup(
            panelTerminiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTerminiLayout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addGroup(panelTerminiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatumTermina)
                    .addComponent(txtDatumTermina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVremePocetkaTermina)
                    .addComponent(txtPocetakTermina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelTerminiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVremeKrajaTermina)
                    .addComponent(txtKrajTermina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVremeKrajaTermina1)
                    .addComponent(txtTrajanjee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
            .addGroup(panelTerminiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelTerminiLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(130, Short.MAX_VALUE)))
        );

        panelNaloziClanova.setBackground(new java.awt.Color(0, 0, 0));
        panelNaloziClanova.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nalozi članova", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        tblNaloziClanova.setBackground(new java.awt.Color(0, 0, 0));
        tblNaloziClanova.setFont(new java.awt.Font("Microsoft YaHei", 0, 11)); // NOI18N
        tblNaloziClanova.setForeground(new java.awt.Color(255, 255, 255));
        tblNaloziClanova.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblNaloziClanova.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tblNaloziClanova);

        btnDodajNalogUTabelu.setBackground(new java.awt.Color(255, 255, 255));
        btnDodajNalogUTabelu.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        btnDodajNalogUTabelu.setText("Dodaj nalog u tabelu");
        btnDodajNalogUTabelu.setBorder(null);

        btnOmoguciDodavanjeViseNaloga.setBackground(new java.awt.Color(255, 255, 255));
        btnOmoguciDodavanjeViseNaloga.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        btnOmoguciDodavanjeViseNaloga.setText("Omoguci SK");
        btnOmoguciDodavanjeViseNaloga.setBorder(null);

        javax.swing.GroupLayout panelNaloziClanovaLayout = new javax.swing.GroupLayout(panelNaloziClanova);
        panelNaloziClanova.setLayout(panelNaloziClanovaLayout);
        panelNaloziClanovaLayout.setHorizontalGroup(
            panelNaloziClanovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNaloziClanovaLayout.createSequentialGroup()
                .addContainerGap(266, Short.MAX_VALUE)
                .addComponent(btnOmoguciDodavanjeViseNaloga, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDodajNalogUTabelu, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panelNaloziClanovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelNaloziClanovaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelNaloziClanovaLayout.setVerticalGroup(
            panelNaloziClanovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNaloziClanovaLayout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addGroup(panelNaloziClanovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodajNalogUTabelu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOmoguciDodavanjeViseNaloga, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(panelNaloziClanovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelNaloziClanovaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panelPrisustvoTerminu2.setBackground(new java.awt.Color(0, 0, 0));
        panelPrisustvoTerminu2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PrisustvaTerminu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        panelPrisustvoTerminu2.setOpaque(false);

        tblPrisustvaa.setBackground(new java.awt.Color(0, 0, 0));
        tblPrisustvaa.setFont(new java.awt.Font("Microsoft YaHei", 0, 11)); // NOI18N
        tblPrisustvaa.setForeground(new java.awt.Color(255, 255, 255));
        tblPrisustvaa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPrisustvaa.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane6.setViewportView(tblPrisustvaa);

        javax.swing.GroupLayout panelPrisustvoTerminu2Layout = new javax.swing.GroupLayout(panelPrisustvoTerminu2);
        panelPrisustvoTerminu2.setLayout(panelPrisustvoTerminu2Layout);
        panelPrisustvoTerminu2Layout.setHorizontalGroup(
            panelPrisustvoTerminu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrisustvoTerminu2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6)
                .addContainerGap())
        );
        panelPrisustvoTerminu2Layout.setVerticalGroup(
            panelPrisustvoTerminu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrisustvoTerminu2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addGap(46, 46, 46))
        );

        btnDodajNalogUTermin.setBackground(new java.awt.Color(255, 255, 255));
        btnDodajNalogUTermin.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        btnDodajNalogUTermin.setText("Dodaj nalog člana u termin ");
        btnDodajNalogUTermin.setBorder(null);

        lblError.setBackground(new java.awt.Color(0, 0, 0));
        lblError.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 0, 51));

        panelNaloziClanovaDodati.setBackground(new java.awt.Color(0, 0, 0));
        panelNaloziClanovaDodati.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nalozi članova za dodavanje", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        tblNaloziClanovaZaDodavanje.setBackground(new java.awt.Color(0, 0, 0));
        tblNaloziClanovaZaDodavanje.setFont(new java.awt.Font("Microsoft YaHei", 0, 11)); // NOI18N
        tblNaloziClanovaZaDodavanje.setForeground(new java.awt.Color(255, 255, 255));
        tblNaloziClanovaZaDodavanje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblNaloziClanovaZaDodavanje.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(tblNaloziClanovaZaDodavanje);

        btnDodajNalogeUTermin.setBackground(new java.awt.Color(255, 255, 255));
        btnDodajNalogeUTermin.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        btnDodajNalogeUTermin.setText("Dodaj naloge u termin");
        btnDodajNalogeUTermin.setBorder(null);

        javax.swing.GroupLayout panelNaloziClanovaDodatiLayout = new javax.swing.GroupLayout(panelNaloziClanovaDodati);
        panelNaloziClanovaDodati.setLayout(panelNaloziClanovaDodatiLayout);
        panelNaloziClanovaDodatiLayout.setHorizontalGroup(
            panelNaloziClanovaDodatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNaloziClanovaDodatiLayout.createSequentialGroup()
                .addContainerGap(455, Short.MAX_VALUE)
                .addComponent(btnDodajNalogeUTermin, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panelNaloziClanovaDodatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelNaloziClanovaDodatiLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelNaloziClanovaDodatiLayout.setVerticalGroup(
            panelNaloziClanovaDodatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNaloziClanovaDodatiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDodajNalogeUTermin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panelNaloziClanovaDodatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelNaloziClanovaDodatiLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(61, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTermini, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackgroundLayout.createSequentialGroup()
                        .addComponent(lblError)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDodajNalogUTermin, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelPrisustvoTerminu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addComponent(panelNaloziClanova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelNaloziClanovaDodati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelNaloziClanova, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelNaloziClanovaDodati, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(panelTermini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDodajNalogUTermin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblError))
                .addGap(18, 18, 18)
                .addComponent(panelPrisustvoTerminu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnDodajNalogUTabelu;
    private javax.swing.JToggleButton btnDodajNalogUTermin;
    private javax.swing.JToggleButton btnDodajNalogeUTermin;
    private javax.swing.JToggleButton btnOmoguciDodavanjeViseNaloga;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblDatumTermina;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblVremeKrajaTermina;
    private javax.swing.JLabel lblVremeKrajaTermina1;
    private javax.swing.JLabel lblVremePocetkaTermina;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelNaloziClanova;
    private javax.swing.JPanel panelNaloziClanovaDodati;
    private javax.swing.JPanel panelPrisustvoTerminu2;
    private javax.swing.JPanel panelTermini;
    private javax.swing.JTable tblNaloziClanova;
    private javax.swing.JTable tblNaloziClanovaZaDodavanje;
    private javax.swing.JTable tblPrisustvaa;
    private javax.swing.JTable tblTermini;
    private javax.swing.JTextField txtDatumTermina;
    private javax.swing.JTextField txtKrajTermina;
    private javax.swing.JTextField txtPocetakTermina;
    private javax.swing.JTextField txtTrajanjee;
    // End of variables declaration//GEN-END:variables

    public void btnDodajNalogeUTerminAddActionListener(ActionListener al){
        btnDodajNalogeUTermin.addActionListener(al);
    }
    
    public void btnDodajNalogUTerminAddActionListener(ActionListener al){
        btnDodajNalogUTermin.addActionListener(al);
    }
    
    public void btnOmoguciSKAddActionListener(ActionListener al){
        btnOmoguciDodavanjeViseNaloga.addActionListener(al);
    }
    
    public void btnDodajViseNalogaAddActionListener(ActionListener al){
        btnDodajNalogUTabelu.addActionListener(al);
    }
    
    public void mouseClickedTblTermin(MouseListener ml){
        tblTermini.addMouseListener(ml);
    }
    
    public void mouseClickedTblNalozi(MouseListener ml){
        tblNaloziClanova.addMouseListener(ml);
    }
    
    public javax.swing.JToggleButton getBtnDodajNalogUTermin() {
        return btnDodajNalogUTermin;
    }

    public void setBtnDodajNalogUTermin(javax.swing.JToggleButton btnDodajNalogUTermin) {
        this.btnDodajNalogUTermin = btnDodajNalogUTermin;
    }
    
    

    public javax.swing.JTable getTblNaloziClanova() {
        return tblNaloziClanova;
    }

    public void setTblNaloziClanova(javax.swing.JTable tblNaloziClanova) {
        this.tblNaloziClanova = tblNaloziClanova;
    }

    public javax.swing.JTable getTblPrisustvaa() {
        return tblPrisustvaa;
    }

    public void setTblPrisustvaa(javax.swing.JTable tblPrisustvaa) {
        this.tblPrisustvaa = tblPrisustvaa;
    }

    public javax.swing.JTable getTblTermini() {
        return tblTermini;
    }

    public void setTblTermini(javax.swing.JTable tblTermini) {
        this.tblTermini = tblTermini;
    }

    public javax.swing.JTextField getTxtDatumTermina() {
        return txtDatumTermina;
    }

    public void setTxtDatumTermina(javax.swing.JTextField txtDatumTermina) {
        this.txtDatumTermina = txtDatumTermina;
    }

    public javax.swing.JTextField getTxtKrajTermina() {
        return txtKrajTermina;
    }

    public void setTxtKrajTermina(javax.swing.JTextField txtKrajTermina) {
        this.txtKrajTermina = txtKrajTermina;
    }

    public javax.swing.JTextField getTxtPocetakTermina() {
        return txtPocetakTermina;
    }

    public void setTxtPocetakTermina(javax.swing.JTextField txtPocetakTermina) {
        this.txtPocetakTermina = txtPocetakTermina;
    }

    public javax.swing.JTextField getTxtTrajanjee() {
        return txtTrajanjee;
    }

    public void setTxtTrajanjee(javax.swing.JTextField txtTrajanjee) {
        this.txtTrajanjee = txtTrajanjee;
    }

    public javax.swing.JLabel getLblError() {
        return lblError;
    }

    public void setLblError(javax.swing.JLabel lblError) {
        this.lblError = lblError;
    }

    public javax.swing.JToggleButton getBtnDodajNalogUTabelu() {
        return btnDodajNalogUTabelu;
    }

    public void setBtnDodajNalogUTabelu(javax.swing.JToggleButton btnDodajNalogUTabelu) {
        this.btnDodajNalogUTabelu = btnDodajNalogUTabelu;
    }

    public javax.swing.JToggleButton getBtnOmoguciDodavanjeViseNaloga() {
        return btnOmoguciDodavanjeViseNaloga;
    }

    public void setBtnOmoguciDodavanjeViseNaloga(javax.swing.JToggleButton btnOmoguciDodavanjeViseNaloga) {
        this.btnOmoguciDodavanjeViseNaloga = btnOmoguciDodavanjeViseNaloga;
    }

    public javax.swing.JTable getTblNaloziClanovaZaDodavanje() {
        return tblNaloziClanovaZaDodavanje;
    }

    public void setTblNaloziClanovaZaDodavanje(javax.swing.JTable tblNaloziClanovaZaDodavanje) {
        this.tblNaloziClanovaZaDodavanje = tblNaloziClanovaZaDodavanje;
    }

    public javax.swing.JToggleButton getBtnDodajNalogeUTermin() {
        return btnDodajNalogeUTermin;
    }

    public void setBtnDodajNalogeUTermin(javax.swing.JToggleButton btnDodajNalogeUTermin) {
        this.btnDodajNalogeUTermin = btnDodajNalogeUTermin;
    }
    
    
}


