/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view.forms;

import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import rs.ac.bg.fon.ps.domain.Trener;
import rs.ac.bg.fon.ps.exceptions.ValidationException;
import rs.ac.bg.fon.ps.view.controllers.ViewController;

/**
 *
 * @author Mr OLOGIZ
 */
public class FrmLogIn extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogIn
     */
    public FrmLogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lblPasswordError = new javax.swing.JLabel();
        lblUsernameError = new javax.swing.JLabel();
        btnLogIn = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(680, 680));
        setPreferredSize(new java.awt.Dimension(687, 686));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsername.setBackground(new java.awt.Color(0, 0, 0));
        txtUsername.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtUsername.setBorder(null);
        txtUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUsername.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtUsername.setOpaque(false);
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 460, 60));

        txtPassword.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setBorder(null);
        txtPassword.setOpaque(false);
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 470, 60));

        lblPasswordError.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblPasswordError.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(lblPasswordError, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 480, 40));

        lblUsernameError.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblUsernameError.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(lblUsernameError, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 480, 40));

        btnLogIn.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        btnLogIn.setText("Uloguj se");
        btnLogIn.setBorder(null);
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 290, 90));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/ac/bg/fon/ps/images/LogInBackground.png"))); // NOI18N
        lblBackground.setMaximumSize(new java.awt.Dimension(900, 900));
        lblBackground.setMinimumSize(new java.awt.Dimension(680, 680));
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        /*resetForm();
        try {
            validateForm();           
            Trener trener=Controller.getInstance().logIn(txtUsername.getText(), String.valueOf(txtPassword.getPassword()));
            ViewController.getInstance().setLogedTrener(trener);
            
            JOptionPane.showMessageDialog(this, "Ulogovan trener: "+trener,"Logovanje",JOptionPane.INFORMATION_MESSAGE);
            ViewController.getInstance().openMainForm();
            
        } catch (ValidationException ex) {
            ex.printStackTrace();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Greska u logovanju",JOptionPane.ERROR_MESSAGE);
        }*/

    }//GEN-LAST:event_btnLogInActionPerformed

   /* private void validateForm() throws ValidationException{
        String errorMessage="";
        if(txtUsername.getText().isEmpty()){
            lblUsernameError.setText("Korisnicko ime ne sme biti prazno");
            errorMessage+="Korisnicko ime ne sme biti prazno\n";
        }
        if(String.valueOf(txtPassword.getPassword()).isEmpty()){
            lblPasswordError.setText("Sifra ne sme bitri prazna");
            errorMessage+="Sifra ne sme biti prazna\n";
        }
        
        if(!errorMessage.isEmpty()){
            throw new ValidationException(errorMessage);
        }
    }*/
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogIn;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblPasswordError;
    private javax.swing.JLabel lblUsernameError;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

   /* private void resetForm() {
        lblUsernameError.setText("");
        lblPasswordError.setText("");
    }*/
    
     public void loginAddActionListener(ActionListener actionListener) {
        btnLogIn.addActionListener(actionListener);
    }

    public JButton getBtnLogIn() {
        return btnLogIn;
    }

    public void setBtnLogIn(JButton btnLogIn) {
        this.btnLogIn = btnLogIn;
    }

    public JLabel getLblBackground() {
        return lblBackground;
    }

    public void setLblBackground(JLabel lblBackground) {
        this.lblBackground = lblBackground;
    }

    public JLabel getLblPasswordError() {
        return lblPasswordError;
    }

    public void setLblPasswordError(JLabel lblPasswordError) {
        this.lblPasswordError = lblPasswordError;
    }

    public JLabel getLblUsernameError() {
        return lblUsernameError;
    }

    public void setLblUsernameError(JLabel lblUsernameError) {
        this.lblUsernameError = lblUsernameError;
    }

    public JPasswordField getTxtPassword() {
        return txtPassword;
    }

    public void setTxtPassword(JPasswordField txtPassword) {
        this.txtPassword = txtPassword;
    }

    public JTextField getTxtUsername() {
        return txtUsername;
    }

    public void setTxtUsername(JTextField txtUsername) {
        this.txtUsername = txtUsername;
    }
     
     

}
