/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view.forms;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenuItem;

/**
 *
 * @author Mr OLOGIZ
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        lblUlogovanTrener = new javax.swing.JLabel();
        lblUserIcon = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnIzlogujSe = new javax.swing.JButton();
        menuBarMain = new javax.swing.JMenuBar();
        menuNalogClana = new javax.swing.JMenu();
        miRegistrovanjeNalogaClana = new javax.swing.JMenuItem();
        miPretragaNalogaClana = new javax.swing.JMenuItem();
        miDodajNalogClanaUTermin = new javax.swing.JMenuItem();
        menuTermin = new javax.swing.JMenu();
        miRegistorvanjeTermina = new javax.swing.JMenuItem();
        miPretragaTermina = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBackground.setBackground(new java.awt.Color(0, 0, 0));

        lblUlogovanTrener.setBackground(new java.awt.Color(0, 0, 0));
        lblUlogovanTrener.setFont(new java.awt.Font("Microsoft YaHei", 0, 36)); // NOI18N
        lblUlogovanTrener.setForeground(new java.awt.Color(255, 255, 255));
        lblUlogovanTrener.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUlogovanTrener.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/ac/bg/fon/ps/images/user icon 2.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        btnIzlogujSe.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        btnIzlogujSe.setText("Izloguj se");
        btnIzlogujSe.setBorder(null);
        btnIzlogujSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzlogujSeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addComponent(lblUserIcon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblUlogovanTrener, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackgroundLayout.createSequentialGroup()
                        .addContainerGap(832, Short.MAX_VALUE)
                        .addComponent(btnIzlogujSe, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserIcon)
                    .addComponent(lblUlogovanTrener, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnIzlogujSe, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        menuNalogClana.setText("Nalog člana");

        miRegistrovanjeNalogaClana.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        miRegistrovanjeNalogaClana.setText("Registrovanje ");
        miRegistrovanjeNalogaClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRegistrovanjeNalogaClanaActionPerformed(evt);
            }
        });
        menuNalogClana.add(miRegistrovanjeNalogaClana);

        miPretragaNalogaClana.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        miPretragaNalogaClana.setText("Pretraga");
        miPretragaNalogaClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaNalogaClanaActionPerformed(evt);
            }
        });
        menuNalogClana.add(miPretragaNalogaClana);

        miDodajNalogClanaUTermin.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        miDodajNalogClanaUTermin.setText("Dodavanje naloga člana u termin");
        miDodajNalogClanaUTermin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDodajNalogClanaUTerminActionPerformed(evt);
            }
        });
        menuNalogClana.add(miDodajNalogClanaUTermin);

        menuBarMain.add(menuNalogClana);

        menuTermin.setText("Termin");

        miRegistorvanjeTermina.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        miRegistorvanjeTermina.setText("Registrovanje");
        menuTermin.add(miRegistorvanjeTermina);

        miPretragaTermina.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        miPretragaTermina.setText("Pretraga");
        miPretragaTermina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaTerminaActionPerformed(evt);
            }
        });
        menuTermin.add(miPretragaTermina);

        menuBarMain.add(menuTermin);

        setJMenuBar(menuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miPretragaTerminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaTerminaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miPretragaTerminaActionPerformed

    private void miRegistrovanjeNalogaClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRegistrovanjeNalogaClanaActionPerformed

    }//GEN-LAST:event_miRegistrovanjeNalogaClanaActionPerformed

    private void miPretragaNalogaClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaNalogaClanaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miPretragaNalogaClanaActionPerformed

    private void btnIzlogujSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzlogujSeActionPerformed

    }//GEN-LAST:event_btnIzlogujSeActionPerformed

    private void miDodajNalogClanaUTerminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDodajNalogClanaUTerminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miDodajNalogClanaUTerminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzlogujSe;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblUlogovanTrener;
    private javax.swing.JLabel lblUserIcon;
    private javax.swing.JMenuBar menuBarMain;
    private javax.swing.JMenu menuNalogClana;
    private javax.swing.JMenu menuTermin;
    private javax.swing.JMenuItem miDodajNalogClanaUTermin;
    private javax.swing.JMenuItem miPretragaNalogaClana;
    private javax.swing.JMenuItem miPretragaTermina;
    private javax.swing.JMenuItem miRegistorvanjeTermina;
    private javax.swing.JMenuItem miRegistrovanjeNalogaClana;
    private javax.swing.JPanel panelBackground;
    // End of variables declaration//GEN-END:variables

    private void resetForm() {
    }

    public JButton getBtnIzlogujSe() {
        return btnIzlogujSe;
    }

    public void setBtnIzlogujSe(JButton btnIzlogujSe) {
        this.btnIzlogujSe = btnIzlogujSe;
    }

    public JLabel getLblUlogovanTrener() {
        return lblUlogovanTrener;
    }

    public void setLblUlogovanTrener(JLabel lblUlogovanTrener) {
        this.lblUlogovanTrener = lblUlogovanTrener;
    }

    public JMenuItem getMiPretragaNalogaClana() {
        return miPretragaNalogaClana;
    }

    public void setMiPretragaNalogaClana(JMenuItem miPretragaNalogaClana) {
        this.miPretragaNalogaClana = miPretragaNalogaClana;
    }

    public JMenuItem getMiPretragaTermina() {
        return miPretragaTermina;
    }

    public void setMiPretragaTermina(JMenuItem miPretragaTermina) {
        this.miPretragaTermina = miPretragaTermina;
    }

    public JMenuItem getMiRegistorvanjeTermina() {
        return miRegistorvanjeTermina;
    }

    public void setMiRegistorvanjeTermina(JMenuItem miRegistorvanjeTermina) {
        this.miRegistorvanjeTermina = miRegistorvanjeTermina;
    }

    public JMenuItem getMiRegistrovanjeNalogaClana() {
        return miRegistrovanjeNalogaClana;
    }

    public void setMiRegistrovanjeNalogaClana(JMenuItem miRegistrovanjeNalogaClana) {
        this.miRegistrovanjeNalogaClana = miRegistrovanjeNalogaClana;
    }

    public void miNalogClanaNewAddActionListener(ActionListener actionListener) {
        miRegistrovanjeNalogaClana.addActionListener(actionListener);
    }

    public void miNalogClanaSearchAddActionListener(ActionListener actionListener) {
        miPretragaNalogaClana.addActionListener(actionListener);
    }

    public void miTerminNewAddActionListener(ActionListener actionListener) {
        miRegistorvanjeTermina.addActionListener(actionListener);
    }

    public void miPretraziTerminAddActionListener(ActionListener actionListener) {
        miPretragaTermina.addActionListener(actionListener);
    }

    public void miDodajNalogUTermin(ActionListener actionListener) {
        miDodajNalogClanaUTermin.addActionListener(actionListener); 
    }
    
    public void izlogujSeBtnAddActionListener(ActionListener al){
        btnIzlogujSe.addActionListener(al);
    }

}
