/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view.forms;

import java.awt.event.ActionListener;

/**
 *
 * @author Mr OLOGIZ
 */
public class FrmNalogClanaCRUD extends javax.swing.JDialog {

    /**
     * Creates new form FrmNalogClanaCRUD
     */
    public FrmNalogClanaCRUD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPlatio = new javax.swing.ButtonGroup();
        bgPol = new javax.swing.ButtonGroup();
        panelBackGround = new javax.swing.JPanel();
        lblIdClana = new javax.swing.JLabel();
        lblImeClana = new javax.swing.JLabel();
        lblPrezimeClana = new javax.swing.JLabel();
        lblBrojTelefonaClana = new javax.swing.JLabel();
        lblUlicaBroj = new javax.swing.JLabel();
        lblPlatio = new javax.swing.JLabel();
        lblJBMG = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        txtUlicaBroj = new javax.swing.JTextField();
        txtBrojTelefona1 = new javax.swing.JTextField();
        txtJBMG = new javax.swing.JTextField();
        rbDa = new javax.swing.JRadioButton();
        rbNe = new javax.swing.JRadioButton();
        lblPol = new javax.swing.JLabel();
        rbMuski = new javax.swing.JRadioButton();
        rbZenski = new javax.swing.JRadioButton();
        rbOstalo = new javax.swing.JRadioButton();
        lblBackground = new javax.swing.JLabel();
        btnObrisiNalog = new javax.swing.JButton();
        btnPotvrdiIzmene = new javax.swing.JButton();
        btnOmoguciIzmene = new javax.swing.JButton();
        lblErrorMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelBackGround.setBackground(new java.awt.Color(0, 0, 0));
        panelBackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIdClana.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblIdClana.setForeground(new java.awt.Color(255, 255, 255));
        lblIdClana.setText("id:");
        panelBackGround.add(lblIdClana, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 9, -1, -1));

        lblImeClana.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblImeClana.setForeground(new java.awt.Color(255, 255, 255));
        lblImeClana.setText("ime:");
        panelBackGround.add(lblImeClana, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 39, -1, -1));

        lblPrezimeClana.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblPrezimeClana.setForeground(new java.awt.Color(255, 255, 255));
        lblPrezimeClana.setText("prezime:");
        panelBackGround.add(lblPrezimeClana, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 71, -1, -1));

        lblBrojTelefonaClana.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblBrojTelefonaClana.setForeground(new java.awt.Color(255, 255, 255));
        lblBrojTelefonaClana.setText("broj telefona:");
        panelBackGround.add(lblBrojTelefonaClana, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 106, -1, -1));

        lblUlicaBroj.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblUlicaBroj.setForeground(new java.awt.Color(255, 255, 255));
        lblUlicaBroj.setText("ulica i broj (sprat i stan):");
        panelBackGround.add(lblUlicaBroj, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 141, -1, -1));

        lblPlatio.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblPlatio.setForeground(new java.awt.Color(255, 255, 255));
        lblPlatio.setText("platio/platila:");
        panelBackGround.add(lblPlatio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 179, -1, -1));

        lblJBMG.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblJBMG.setForeground(new java.awt.Color(255, 255, 255));
        lblJBMG.setText("JBMG:");
        panelBackGround.add(lblJBMG, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        txtId.setBackground(new java.awt.Color(0, 0, 0));
        txtId.setForeground(new java.awt.Color(255, 255, 255));
        txtId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panelBackGround.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 10, 230, -1));

        txtIme.setBackground(new java.awt.Color(0, 0, 0));
        txtIme.setForeground(new java.awt.Color(255, 255, 255));
        txtIme.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panelBackGround.add(txtIme, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 40, 230, -1));

        txtPrezime.setBackground(new java.awt.Color(0, 0, 0));
        txtPrezime.setForeground(new java.awt.Color(255, 255, 255));
        txtPrezime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panelBackGround.add(txtPrezime, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 72, 230, -1));

        txtUlicaBroj.setBackground(new java.awt.Color(0, 0, 0));
        txtUlicaBroj.setForeground(new java.awt.Color(255, 255, 255));
        txtUlicaBroj.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panelBackGround.add(txtUlicaBroj, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 142, 230, -1));

        txtBrojTelefona1.setBackground(new java.awt.Color(0, 0, 0));
        txtBrojTelefona1.setForeground(new java.awt.Color(255, 255, 255));
        txtBrojTelefona1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panelBackGround.add(txtBrojTelefona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 107, 230, -1));

        txtJBMG.setBackground(new java.awt.Color(0, 0, 0));
        txtJBMG.setForeground(new java.awt.Color(255, 255, 255));
        txtJBMG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panelBackGround.add(txtJBMG, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 259, 230, -1));

        rbDa.setBackground(new java.awt.Color(0, 0, 0));
        bgPlatio.add(rbDa);
        rbDa.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        rbDa.setForeground(new java.awt.Color(255, 255, 255));
        rbDa.setText("da");
        panelBackGround.add(rbDa, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 176, -1, -1));

        rbNe.setBackground(new java.awt.Color(0, 0, 0));
        bgPlatio.add(rbNe);
        rbNe.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        rbNe.setForeground(new java.awt.Color(255, 255, 255));
        rbNe.setText("ne");
        panelBackGround.add(rbNe, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 176, -1, -1));

        lblPol.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblPol.setForeground(new java.awt.Color(255, 255, 255));
        lblPol.setText("pol:");
        panelBackGround.add(lblPol, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        rbMuski.setBackground(new java.awt.Color(0, 0, 0));
        bgPol.add(rbMuski);
        rbMuski.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        rbMuski.setForeground(new java.awt.Color(255, 255, 255));
        rbMuski.setText("muski");
        panelBackGround.add(rbMuski, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 217, -1, -1));

        rbZenski.setBackground(new java.awt.Color(0, 0, 0));
        bgPol.add(rbZenski);
        rbZenski.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        rbZenski.setForeground(new java.awt.Color(255, 255, 255));
        rbZenski.setText("zenski");
        panelBackGround.add(rbZenski, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 217, -1, -1));

        rbOstalo.setBackground(new java.awt.Color(0, 0, 0));
        bgPol.add(rbOstalo);
        rbOstalo.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        rbOstalo.setForeground(new java.awt.Color(255, 255, 255));
        rbOstalo.setText("ostalo");
        panelBackGround.add(rbOstalo, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 217, -1, -1));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/ac/bg/fon/ps/images/weightv2.png"))); // NOI18N
        panelBackGround.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 300, -1));

        btnObrisiNalog.setBackground(new java.awt.Color(255, 255, 255));
        btnObrisiNalog.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        btnObrisiNalog.setText("Obriši nalog");
        panelBackGround.add(btnObrisiNalog, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 140, -1));

        btnPotvrdiIzmene.setBackground(new java.awt.Color(255, 255, 255));
        btnPotvrdiIzmene.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        btnPotvrdiIzmene.setText("Potvrdi promene");
        panelBackGround.add(btnPotvrdiIzmene, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 140, -1));

        btnOmoguciIzmene.setBackground(new java.awt.Color(255, 255, 255));
        btnOmoguciIzmene.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        btnOmoguciIzmene.setText("Omogući promene");
        panelBackGround.add(btnOmoguciIzmene, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 140, -1));

        lblErrorMessage.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblErrorMessage.setForeground(new java.awt.Color(255, 0, 51));
        panelBackGround.add(lblErrorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackGround, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(panelBackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void OmoguciIzmeneNalogaAddActionListener(ActionListener actionListener) {
        btnOmoguciIzmene.addActionListener(actionListener);
    }

    public void ObrisiNalogAddActionListener(ActionListener actionListener) {
        btnObrisiNalog.addActionListener(actionListener);
    }

    public void IzmeniNalogAddActionListener(ActionListener actionListener) {
        btnPotvrdiIzmene.addActionListener(actionListener);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgPlatio;
    private javax.swing.ButtonGroup bgPol;
    private javax.swing.JButton btnObrisiNalog;
    private javax.swing.JButton btnOmoguciIzmene;
    private javax.swing.JButton btnPotvrdiIzmene;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBrojTelefonaClana;
    private javax.swing.JLabel lblErrorMessage;
    private javax.swing.JLabel lblIdClana;
    private javax.swing.JLabel lblImeClana;
    private javax.swing.JLabel lblJBMG;
    private javax.swing.JLabel lblPlatio;
    private javax.swing.JLabel lblPol;
    private javax.swing.JLabel lblPrezimeClana;
    private javax.swing.JLabel lblUlicaBroj;
    private javax.swing.JPanel panelBackGround;
    private javax.swing.JRadioButton rbDa;
    private javax.swing.JRadioButton rbMuski;
    private javax.swing.JRadioButton rbNe;
    private javax.swing.JRadioButton rbOstalo;
    private javax.swing.JRadioButton rbZenski;
    private javax.swing.JTextField txtBrojTelefona1;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtJBMG;
    private javax.swing.JTextField txtPrezime;
    private javax.swing.JTextField txtUlicaBroj;
    // End of variables declaration//GEN-END:variables

    
    
    public javax.swing.ButtonGroup getBgPlatio() {
        return bgPlatio;
    }

    public void setBgPlatio(javax.swing.ButtonGroup bgPlatio) {
        this.bgPlatio = bgPlatio;
    }

    public javax.swing.ButtonGroup getBgPol() {
        return bgPol;
    }

    public void setBgPol(javax.swing.ButtonGroup bgPol) {
        this.bgPol = bgPol;
    }

    public javax.swing.JButton getBtnObrisiNalog() {
        return btnObrisiNalog;
    }

    public void setBtnObrisiNalog(javax.swing.JButton btnObrisiNalog) {
        this.btnObrisiNalog = btnObrisiNalog;
    }

    public javax.swing.JButton getBtnOmoguciIzmene() {
        return btnOmoguciIzmene;
    }

    public void setBtnOmoguciIzmene(javax.swing.JButton btnOmoguciIzmene) {
        this.btnOmoguciIzmene = btnOmoguciIzmene;
    }

    public javax.swing.JButton getBtnPotvrdiIzmene() {
        return btnPotvrdiIzmene;
    }

    public void setBtnPotvrdiIzmene(javax.swing.JButton btnPotvrdiIzmene) {
        this.btnPotvrdiIzmene = btnPotvrdiIzmene;
    }

    public javax.swing.JRadioButton getRbDa() {
        return rbDa;
    }

    public void setRbDa(javax.swing.JRadioButton rbDa) {
        this.rbDa = rbDa;
    }

    public javax.swing.JRadioButton getRbMuski() {
        return rbMuski;
    }

    public void setRbMuski(javax.swing.JRadioButton rbMuski) {
        this.rbMuski = rbMuski;
    }

    public javax.swing.JRadioButton getRbNe() {
        return rbNe;
    }

    public void setRbNe(javax.swing.JRadioButton rbNe) {
        this.rbNe = rbNe;
    }

    public javax.swing.JRadioButton getRbOstalo() {
        return rbOstalo;
    }

    public void setRbOstalo(javax.swing.JRadioButton rbOstalo) {
        this.rbOstalo = rbOstalo;
    }

    public javax.swing.JRadioButton getRbZenski() {
        return rbZenski;
    }

    public void setRbZenski(javax.swing.JRadioButton rbZenski) {
        this.rbZenski = rbZenski;
    }

    public javax.swing.JTextField getTxtBrojTelefona1() {
        return txtBrojTelefona1;
    }

    public void setTxtBrojTelefona1(javax.swing.JTextField txtBrojTelefona1) {
        this.txtBrojTelefona1 = txtBrojTelefona1;
    }

    public javax.swing.JTextField getTxtId() {
        return txtId;
    }

    public void setTxtId(javax.swing.JTextField txtId) {
        this.txtId = txtId;
    }

    public javax.swing.JTextField getTxtIme() {
        return txtIme;
    }

    public void setTxtIme(javax.swing.JTextField txtIme) {
        this.txtIme = txtIme;
    }

    public javax.swing.JTextField getTxtJBMG() {
        return txtJBMG;
    }

    public void setTxtJBMG(javax.swing.JTextField txtJBMG) {
        this.txtJBMG = txtJBMG;
    }

    public javax.swing.JTextField getTxtPrezime() {
        return txtPrezime;
    }

    public void setTxtPrezime(javax.swing.JTextField txtPrezime) {
        this.txtPrezime = txtPrezime;
    }

    public javax.swing.JTextField getTxtUlicaBroj() {
        return txtUlicaBroj;
    }

    public void setTxtUlicaBroj(javax.swing.JTextField txtUlicaBroj) {
        this.txtUlicaBroj = txtUlicaBroj;
    }

    public javax.swing.JLabel getLblErrorMessage() {
        return lblErrorMessage;
    }

    public void setLblErrorMessage(javax.swing.JLabel lblErrorMessage) {
        this.lblErrorMessage = lblErrorMessage;
    }
}
