/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view.forms;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.beans.PropertyChangeListener;

/**
 *
 * @author Mr OLOGIZ
 */
public class FrmPretragaTermina extends javax.swing.JDialog {

    /**
     * Creates new form FrmPretragaTermina
     */
    public FrmPretragaTermina(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        panelBackground = new javax.swing.JPanel();
        panelSviTermini = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTermini = new javax.swing.JTable();
        lblDatumTermina = new javax.swing.JLabel();
        lblVremeKrajaTermina = new javax.swing.JLabel();
        txtDatumTermina = new javax.swing.JTextField();
        txtPocetakTermina = new javax.swing.JTextField();
        lblVremePocetkaTermina = new javax.swing.JLabel();
        txtKrajTermina = new javax.swing.JTextField();
        txtTrajanje = new javax.swing.JTextField();
        lblVremeKrajaTermina1 = new javax.swing.JLabel();
        btnUcitajTermin = new javax.swing.JToggleButton();
        lblPoCemuBiStePretrazili1 = new javax.swing.JLabel();
        cbKriterijumPretrage = new javax.swing.JComboBox<>();
        lblPretraziTermine = new javax.swing.JLabel();
        lblLupa = new javax.swing.JLabel();
        txtPretraziValue = new javax.swing.JTextField();
        btnPretrazi = new javax.swing.JToggleButton();
        lblNoResaults = new javax.swing.JLabel();
        panelPtretraziPoDatumu = new javax.swing.JPanel();
        dateChooser = new datechooser.beans.DateChooserCombo();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1058, 500));

        panelBackground.setBackground(new java.awt.Color(0, 0, 0));
        panelBackground.setPreferredSize(new java.awt.Dimension(1100, 600));

        panelSviTermini.setBackground(new java.awt.Color(0, 0, 0));
        panelSviTermini.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Svi termini", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        panelSviTermini.setForeground(new java.awt.Color(255, 255, 255));

        tblTermini.setBackground(new java.awt.Color(0, 0, 0));
        tblTermini.setFont(new java.awt.Font("Microsoft YaHei", 0, 11)); // NOI18N
        tblTermini.setForeground(new java.awt.Color(255, 255, 255));
        tblTermini.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTermini.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(tblTermini);

        lblDatumTermina.setBackground(new java.awt.Color(0, 0, 0));
        lblDatumTermina.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblDatumTermina.setForeground(new java.awt.Color(255, 255, 255));
        lblDatumTermina.setText("Datum termina (yyyy-mm-dd):");

        lblVremeKrajaTermina.setBackground(new java.awt.Color(0, 0, 0));
        lblVremeKrajaTermina.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblVremeKrajaTermina.setForeground(new java.awt.Color(255, 255, 255));
        lblVremeKrajaTermina.setText("Vreme kraja termina:");

        txtDatumTermina.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        txtDatumTermina.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        txtPocetakTermina.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        txtPocetakTermina.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        lblVremePocetkaTermina.setBackground(new java.awt.Color(0, 0, 0));
        lblVremePocetkaTermina.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblVremePocetkaTermina.setForeground(new java.awt.Color(255, 255, 255));
        lblVremePocetkaTermina.setText("Vreme početka termina:");

        txtKrajTermina.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        txtKrajTermina.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        txtTrajanje.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        txtTrajanje.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        lblVremeKrajaTermina1.setBackground(new java.awt.Color(0, 0, 0));
        lblVremeKrajaTermina1.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblVremeKrajaTermina1.setForeground(new java.awt.Color(255, 255, 255));
        lblVremeKrajaTermina1.setText("Trajanje:");

        btnUcitajTermin.setBackground(new java.awt.Color(255, 255, 255));
        btnUcitajTermin.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        btnUcitajTermin.setText("Učitaj termin");
        btnUcitajTermin.setBorder(null);

        javax.swing.GroupLayout panelSviTerminiLayout = new javax.swing.GroupLayout(panelSviTermini);
        panelSviTermini.setLayout(panelSviTerminiLayout);
        panelSviTerminiLayout.setHorizontalGroup(
            panelSviTerminiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSviTerminiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSviTerminiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelSviTerminiLayout.createSequentialGroup()
                        .addGroup(panelSviTerminiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVremePocetkaTermina)
                            .addComponent(lblDatumTermina)
                            .addComponent(lblVremeKrajaTermina)
                            .addComponent(lblVremeKrajaTermina1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelSviTerminiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelSviTerminiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPocetakTermina)
                                .addComponent(txtDatumTermina)
                                .addComponent(txtKrajTermina, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelSviTerminiLayout.createSequentialGroup()
                                .addComponent(txtTrajanje, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUcitajTermin, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSviTerminiLayout.setVerticalGroup(
            panelSviTerminiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSviTerminiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(panelSviTerminiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatumTermina)
                    .addComponent(txtDatumTermina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelSviTerminiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPocetakTermina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVremePocetkaTermina))
                .addGap(22, 22, 22)
                .addGroup(panelSviTerminiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVremeKrajaTermina)
                    .addComponent(txtKrajTermina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelSviTerminiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSviTerminiLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(panelSviTerminiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVremeKrajaTermina1)
                            .addComponent(txtTrajanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSviTerminiLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUcitajTermin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))))
        );

        lblPoCemuBiStePretrazili1.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblPoCemuBiStePretrazili1.setForeground(new java.awt.Color(255, 255, 255));
        lblPoCemuBiStePretrazili1.setText("Po cemu bi ste želeli da izvršite pretragu ?");

        cbKriterijumPretrage.setBackground(new java.awt.Color(204, 204, 204));
        cbKriterijumPretrage.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        cbKriterijumPretrage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbKriterijumPretrage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblPretraziTermine.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblPretraziTermine.setForeground(new java.awt.Color(255, 255, 255));
        lblPretraziTermine.setText("Pretraži termine....");

        lblLupa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/ac/bg/fon/ps/images/mala lupa_1.png"))); // NOI18N

        txtPretraziValue.setBackground(new java.awt.Color(0, 0, 0));
        txtPretraziValue.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        txtPretraziValue.setForeground(new java.awt.Color(255, 255, 255));
        txtPretraziValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        btnPretrazi.setBackground(new java.awt.Color(255, 255, 255));
        btnPretrazi.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        btnPretrazi.setText("Pretraži");
        btnPretrazi.setBorder(null);

        lblNoResaults.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        lblNoResaults.setForeground(new java.awt.Color(255, 0, 51));

        panelPtretraziPoDatumu.setBackground(new java.awt.Color(0, 0, 0));
        panelPtretraziPoDatumu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pretrazi po datumu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        dateChooser.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    dateChooser.setCalendarBackground(new java.awt.Color(0, 0, 0));
    dateChooser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED,
        (java.awt.Color)null,
        (java.awt.Color)null,
        (java.awt.Color)null,
        (java.awt.Color)null));
dateChooser.setCalendarPreferredSize(new java.awt.Dimension(250, 150));
dateChooser.setFieldFont(new java.awt.Font("Microsoft YaHei", java.awt.Font.PLAIN, 12));
dateChooser.setNavigateFont(new java.awt.Font("Microsoft YaHei", java.awt.Font.PLAIN, 12));

javax.swing.GroupLayout panelPtretraziPoDatumuLayout = new javax.swing.GroupLayout(panelPtretraziPoDatumu);
panelPtretraziPoDatumu.setLayout(panelPtretraziPoDatumuLayout);
panelPtretraziPoDatumuLayout.setHorizontalGroup(
    panelPtretraziPoDatumuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(panelPtretraziPoDatumuLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    panelPtretraziPoDatumuLayout.setVerticalGroup(
        panelPtretraziPoDatumuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panelPtretraziPoDatumuLayout.createSequentialGroup()
            .addGap(35, 35, 35)
            .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(45, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
    panelBackground.setLayout(panelBackgroundLayout);
    panelBackgroundLayout.setHorizontalGroup(
        panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panelBackgroundLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelBackgroundLayout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(lblNoResaults, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(lblPretraziTermine, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblPoCemuBiStePretrazili1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBackgroundLayout.createSequentialGroup()
                        .addComponent(lblLupa)
                        .addGap(18, 18, 18)
                        .addComponent(txtPretraziValue))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBackgroundLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(cbKriterijumPretrage, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(panelPtretraziPoDatumu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
            .addComponent(panelSviTermini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(81, 81, 81))
    );
    panelBackgroundLayout.setVerticalGroup(
        panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panelBackgroundLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(panelSviTermini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelBackgroundLayout.createSequentialGroup()
                    .addComponent(lblPoCemuBiStePretrazili1)
                    .addGap(11, 11, 11)
                    .addComponent(cbKriterijumPretrage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(lblPretraziTermine)
                    .addGap(18, 18, 18)
                    .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblLupa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPretraziValue, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(22, 22, 22)
                    .addComponent(lblNoResaults)
                    .addGap(33, 33, 33)
                    .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPtretraziPoDatumu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(44, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 1085, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    public void pretragaTerminaAddActionListener(ActionListener actionListener) {
        btnPretrazi.addActionListener(actionListener);
    }

    public void ucitajTerminAddActionListener(ActionListener actionListener) {
        btnUcitajTermin.addActionListener(actionListener);
    }

    public void promeniNaDatum(ActionListener actionListener) {
        cbKriterijumPretrage.addActionListener(actionListener);
    }

    public void klikNatTabeluTerminaActionListener(MouseListener actionListener) {
        tblTermini.addMouseListener(actionListener);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnPretrazi;
    private javax.swing.JToggleButton btnUcitajTermin;
    private javax.swing.JComboBox<Object> cbKriterijumPretrage;
    private datechooser.beans.DateChooserCombo dateChooser;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDatumTermina;
    private javax.swing.JLabel lblLupa;
    private javax.swing.JLabel lblNoResaults;
    private javax.swing.JLabel lblPoCemuBiStePretrazili1;
    private javax.swing.JLabel lblPretraziTermine;
    private javax.swing.JLabel lblVremeKrajaTermina;
    private javax.swing.JLabel lblVremeKrajaTermina1;
    private javax.swing.JLabel lblVremePocetkaTermina;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelPtretraziPoDatumu;
    private javax.swing.JPanel panelSviTermini;
    private javax.swing.JTable tblTermini;
    private javax.swing.JTextField txtDatumTermina;
    private javax.swing.JTextField txtKrajTermina;
    private javax.swing.JTextField txtPocetakTermina;
    private javax.swing.JTextField txtPretraziValue;
    private javax.swing.JTextField txtTrajanje;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JToggleButton getBtnPretrazi() {
        return btnPretrazi;
    }

    public void setBtnPretrazi(javax.swing.JToggleButton btnPretrazi) {
        this.btnPretrazi = btnPretrazi;
    }

    public javax.swing.JToggleButton getBtnUcitajTermin() {
        return btnUcitajTermin;
    }

    public void setBtnUcitajTermin(javax.swing.JToggleButton btnUcitajTermin) {
        this.btnUcitajTermin = btnUcitajTermin;
    }

    public javax.swing.JComboBox<Object> getCbKriterijumPretrage() {
        return cbKriterijumPretrage;
    }

    public void setCbKriterijumPretrage(javax.swing.JComboBox<Object> cbKriterijumPretrage) {
        this.cbKriterijumPretrage = cbKriterijumPretrage;
    }

    public javax.swing.JLabel getLblNoResaults() {
        return lblNoResaults;
    }

    public void setLblNoResaults(javax.swing.JLabel lblNoResaults) {
        this.lblNoResaults = lblNoResaults;
    }

    public javax.swing.JLabel getLblVremeKrajaTermina() {
        return lblVremeKrajaTermina;
    }

    public void setLblVremeKrajaTermina(javax.swing.JLabel lblVremeKrajaTermina) {
        this.lblVremeKrajaTermina = lblVremeKrajaTermina;
    }

    public javax.swing.JLabel getLblVremeKrajaTermina1() {
        return lblVremeKrajaTermina1;
    }

    public void setLblVremeKrajaTermina1(javax.swing.JLabel lblVremeKrajaTermina1) {
        this.lblVremeKrajaTermina1 = lblVremeKrajaTermina1;
    }

    public javax.swing.JLabel getLblVremePocetkaTermina() {
        return lblVremePocetkaTermina;
    }

    public void setLblVremePocetkaTermina(javax.swing.JLabel lblVremePocetkaTermina) {
        this.lblVremePocetkaTermina = lblVremePocetkaTermina;
    }

    public javax.swing.JTable getTblTermini() {
        return tblTermini;
    }

    public void setTblTermini(javax.swing.JTable tblTermini) {
        this.tblTermini = tblTermini;
    }

    public javax.swing.JTextField getTxtDatumTermina() {
        return txtDatumTermina;
    }

    public void setTxtDatumTermina(javax.swing.JTextField txtDatumTermina) {
        this.txtDatumTermina = txtDatumTermina;
    }

    public javax.swing.JTextField getTxtKrajTermina() {
        return txtKrajTermina;
    }

    public void setTxtKrajTermina(javax.swing.JTextField txtKrajTermina) {
        this.txtKrajTermina = txtKrajTermina;
    }

    public javax.swing.JTextField getTxtPocetakTermina() {
        return txtPocetakTermina;
    }

    public void setTxtPocetakTermina(javax.swing.JTextField txtPocetakTermina) {
        this.txtPocetakTermina = txtPocetakTermina;
    }

    public javax.swing.JTextField getTxtPretraziValue() {
        return txtPretraziValue;
    }

    public void setTxtPretraziValue(javax.swing.JTextField txtPretraziValue) {
        this.txtPretraziValue = txtPretraziValue;
    }

    public javax.swing.JTextField getTxtTrajanje() {
        return txtTrajanje;
    }

    public void setTxtTrajanje(javax.swing.JTextField txtTrajanje) {
        this.txtTrajanje = txtTrajanje;
    }

    public datechooser.beans.DateChooserCombo getDateChooser() {
        return dateChooser;
    }

    public void setDateChooser(datechooser.beans.DateChooserCombo dateChooser) {
        this.dateChooser = dateChooser;
    }

    public javax.swing.JPanel getPanelPtretraziPoDatumu() {
        return panelPtretraziPoDatumu;
    }

    public void setPanelPtretraziPoDatumu(javax.swing.JPanel panelPtretraziPoDatumu) {
        this.panelPtretraziPoDatumu = panelPtretraziPoDatumu;
    }
}
