/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view.forms;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author Mr OLOGIZ
 */
public class FrmPretragaNalogaClanova extends javax.swing.JDialog {

    /**
     * Creates new form FrmPretragaNalogaClanova
     */
    public FrmPretragaNalogaClanova(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPretraga = new javax.swing.JPanel();
        lblUlogovanTrener = new javax.swing.JLabel();
        txtUlogovanTrener = new javax.swing.JTextField();
        btnOmoguciDodavanjeNalogaUTermin = new javax.swing.JToggleButton();
        btnDodajNalogUTermin = new javax.swing.JToggleButton();
        panelRezultati = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRezultati = new javax.swing.JTable();
        btnUcitajNalogClana = new javax.swing.JToggleButton();
        lblPretraziNalogeClanova = new javax.swing.JLabel();
        cbKriterijumPretrage = new javax.swing.JComboBox<>();
        lblLupa = new javax.swing.JLabel();
        txtPretraziValue = new javax.swing.JTextField();
        lblPoCemuBiStePretrazili1 = new javax.swing.JLabel();
        btnPretrazi = new javax.swing.JToggleButton();
        lblNoResaults = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        panelTermini = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTermini = new javax.swing.JTable();
        lblDatumTermina = new javax.swing.JLabel();
        txtDatumTermina = new javax.swing.JTextField();
        lblVremePocetkaTermina = new javax.swing.JLabel();
        txtPocetakTermina = new javax.swing.JTextField();
        lblVremeKrajaTermina = new javax.swing.JLabel();
        txtKrajTermina = new javax.swing.JTextField();
        lblVremeKrajaTermina1 = new javax.swing.JLabel();
        txtTrajanjee = new javax.swing.JTextField();
        panelPrisustvoTerminu = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblPrisustva = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        panelPretraga.setBackground(new java.awt.Color(0, 0, 0));

        lblUlogovanTrener.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblUlogovanTrener.setForeground(new java.awt.Color(255, 255, 255));
        lblUlogovanTrener.setText("Ulogovan trener:");

        txtUlogovanTrener.setBackground(new java.awt.Color(0, 0, 0));
        txtUlogovanTrener.setForeground(new java.awt.Color(255, 255, 255));
        txtUlogovanTrener.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        btnOmoguciDodavanjeNalogaUTermin.setBackground(new java.awt.Color(255, 255, 255));
        btnOmoguciDodavanjeNalogaUTermin.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        btnOmoguciDodavanjeNalogaUTermin.setText("Omogući dodavanje naloga u termin");
        btnOmoguciDodavanjeNalogaUTermin.setBorder(null);

        btnDodajNalogUTermin.setBackground(new java.awt.Color(255, 255, 255));
        btnDodajNalogUTermin.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        btnDodajNalogUTermin.setText("Dodaj nalog u termin");
        btnDodajNalogUTermin.setBorder(null);

        panelRezultati.setBackground(new java.awt.Color(0, 0, 0));
        panelRezultati.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rezultati pretrage", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        tblRezultati.setBackground(new java.awt.Color(0, 0, 0));
        tblRezultati.setFont(new java.awt.Font("Microsoft YaHei", 0, 11)); // NOI18N
        tblRezultati.setForeground(new java.awt.Color(255, 255, 255));
        tblRezultati.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblRezultati.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tblRezultati);

        btnUcitajNalogClana.setBackground(new java.awt.Color(255, 255, 255));
        btnUcitajNalogClana.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        btnUcitajNalogClana.setText("Ucitaj nalog clana");
        btnUcitajNalogClana.setBorder(null);

        javax.swing.GroupLayout panelRezultatiLayout = new javax.swing.GroupLayout(panelRezultati);
        panelRezultati.setLayout(panelRezultatiLayout);
        panelRezultatiLayout.setHorizontalGroup(
            panelRezultatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRezultatiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRezultatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 927, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRezultatiLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUcitajNalogClana, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelRezultatiLayout.setVerticalGroup(
            panelRezultatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRezultatiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnUcitajNalogClana, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        lblPretraziNalogeClanova.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblPretraziNalogeClanova.setForeground(new java.awt.Color(255, 255, 255));
        lblPretraziNalogeClanova.setText("Pretraži naloge članova....");

        cbKriterijumPretrage.setBackground(new java.awt.Color(204, 204, 204));
        cbKriterijumPretrage.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        cbKriterijumPretrage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbKriterijumPretrage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblLupa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/ac/bg/fon/ps/images/mala lupa_1.png"))); // NOI18N

        txtPretraziValue.setBackground(new java.awt.Color(0, 0, 0));
        txtPretraziValue.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        txtPretraziValue.setForeground(new java.awt.Color(255, 255, 255));
        txtPretraziValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblPoCemuBiStePretrazili1.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblPoCemuBiStePretrazili1.setForeground(new java.awt.Color(255, 255, 255));
        lblPoCemuBiStePretrazili1.setText("Po cemu bi ste želeli da izvršite pretragu ?");

        btnPretrazi.setBackground(new java.awt.Color(255, 255, 255));
        btnPretrazi.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        btnPretrazi.setText("Pretraži");
        btnPretrazi.setBorder(null);

        lblNoResaults.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        lblNoResaults.setForeground(new java.awt.Color(255, 0, 51));

        lblError.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 0, 51));

        panelTermini.setBackground(new java.awt.Color(0, 0, 0));
        panelTermini.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Termini", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        tblTermini.setBackground(new java.awt.Color(0, 0, 0));
        tblTermini.setFont(new java.awt.Font("Microsoft YaHei", 0, 11)); // NOI18N
        tblTermini.setForeground(new java.awt.Color(255, 255, 255));
        tblTermini.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTermini.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(tblTermini);

        lblDatumTermina.setBackground(new java.awt.Color(0, 0, 0));
        lblDatumTermina.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblDatumTermina.setForeground(new java.awt.Color(255, 255, 255));
        lblDatumTermina.setText("Datum termina (yyyy-mm-dd):");

        txtDatumTermina.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        txtDatumTermina.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        lblVremePocetkaTermina.setBackground(new java.awt.Color(0, 0, 0));
        lblVremePocetkaTermina.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblVremePocetkaTermina.setForeground(new java.awt.Color(255, 255, 255));
        lblVremePocetkaTermina.setText("Vreme početka termina:");

        txtPocetakTermina.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        txtPocetakTermina.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        lblVremeKrajaTermina.setBackground(new java.awt.Color(0, 0, 0));
        lblVremeKrajaTermina.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblVremeKrajaTermina.setForeground(new java.awt.Color(255, 255, 255));
        lblVremeKrajaTermina.setText("Vreme kraja termina:");

        txtKrajTermina.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        txtKrajTermina.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        lblVremeKrajaTermina1.setBackground(new java.awt.Color(0, 0, 0));
        lblVremeKrajaTermina1.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblVremeKrajaTermina1.setForeground(new java.awt.Color(255, 255, 255));
        lblVremeKrajaTermina1.setText("Trajanje:");

        txtTrajanjee.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        txtTrajanjee.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout panelTerminiLayout = new javax.swing.GroupLayout(panelTermini);
        panelTermini.setLayout(panelTerminiLayout);
        panelTerminiLayout.setHorizontalGroup(
            panelTerminiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTerminiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTerminiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(panelTerminiLayout.createSequentialGroup()
                        .addGroup(panelTerminiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDatumTermina)
                            .addComponent(lblVremeKrajaTermina))
                        .addGap(18, 18, 18)
                        .addGroup(panelTerminiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKrajTermina, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDatumTermina, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(panelTerminiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVremePocetkaTermina)
                            .addComponent(lblVremeKrajaTermina1))
                        .addGap(28, 28, 28)
                        .addGroup(panelTerminiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTrajanjee, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPocetakTermina, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 92, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelTerminiLayout.setVerticalGroup(
            panelTerminiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTerminiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelTerminiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatumTermina)
                    .addComponent(txtDatumTermina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVremePocetkaTermina)
                    .addComponent(txtPocetakTermina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelTerminiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVremeKrajaTermina)
                    .addComponent(txtKrajTermina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVremeKrajaTermina1)
                    .addComponent(txtTrajanjee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        panelPrisustvoTerminu.setBackground(new java.awt.Color(0, 0, 0));
        panelPrisustvoTerminu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PrisustvaTerminu od selektovanog naloga", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        panelPrisustvoTerminu.setOpaque(false);

        tblPrisustva.setBackground(new java.awt.Color(0, 0, 0));
        tblPrisustva.setFont(new java.awt.Font("Microsoft YaHei", 0, 11)); // NOI18N
        tblPrisustva.setForeground(new java.awt.Color(255, 255, 255));
        tblPrisustva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPrisustva.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane4.setViewportView(tblPrisustva);

        javax.swing.GroupLayout panelPrisustvoTerminuLayout = new javax.swing.GroupLayout(panelPrisustvoTerminu);
        panelPrisustvoTerminu.setLayout(panelPrisustvoTerminuLayout);
        panelPrisustvoTerminuLayout.setHorizontalGroup(
            panelPrisustvoTerminuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrisustvoTerminuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelPrisustvoTerminuLayout.setVerticalGroup(
            panelPrisustvoTerminuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrisustvoTerminuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout panelPretragaLayout = new javax.swing.GroupLayout(panelPretraga);
        panelPretraga.setLayout(panelPretragaLayout);
        panelPretragaLayout.setHorizontalGroup(
            panelPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPretragaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPretragaLayout.createSequentialGroup()
                        .addGroup(panelPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPoCemuBiStePretrazili1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPretragaLayout.createSequentialGroup()
                                .addComponent(btnOmoguciDodavanjeNalogaUTermin, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDodajNalogUTermin, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addGroup(panelPretragaLayout.createSequentialGroup()
                                .addGroup(panelPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelPretragaLayout.createSequentialGroup()
                                        .addComponent(lblUlogovanTrener)
                                        .addGap(37, 37, 37)
                                        .addComponent(txtUlogovanTrener, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(panelPretragaLayout.createSequentialGroup()
                                            .addGap(2, 2, 2)
                                            .addComponent(lblLupa)
                                            .addGap(18, 18, 18)
                                            .addGroup(panelPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblNoResaults, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtPretraziValue, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(lblPretraziNalogeClanova, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbKriterijumPretrage, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelRezultati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPretragaLayout.createSequentialGroup()
                        .addComponent(panelPrisustvoTerminu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelTermini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPretragaLayout.createSequentialGroup()
                        .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelPretragaLayout.setVerticalGroup(
            panelPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPretragaLayout.createSequentialGroup()
                .addGroup(panelPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelPretragaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelRezultati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPretragaLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblPoCemuBiStePretrazili1)
                        .addGap(11, 11, 11)
                        .addComponent(cbKriterijumPretrage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUlogovanTrener)
                            .addComponent(txtUlogovanTrener, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addComponent(lblPretraziNalogeClanova)
                        .addGap(27, 27, 27)
                        .addGroup(panelPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblLupa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPretraziValue)
                                .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPretragaLayout.createSequentialGroup()
                                .addComponent(lblNoResaults)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnOmoguciDodavanjeNalogaUTermin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPretragaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnDodajNalogUTermin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTermini, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPrisustvoTerminu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(panelPretraga);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //ovaj tip eventa
    }//GEN-LAST:event_formWindowOpened

    public void prisustvaTerminuOdSelektovanogNalogaAddMouseListener(MouseListener ml){
        tblPrisustva.addMouseListener(ml);
    }
    
    public void rezultatiPretrageNalogaAddMouseListener(MouseListener ml){
        tblRezultati.addMouseListener(ml);
    }
    
    public void pretragaNalogaAddActionListener(ActionListener actionListener) {
        btnPretrazi.addActionListener(actionListener);
    }

    public void OmoguciDodavanjeNalogaAddActionListener(ActionListener actionListener) {
        btnOmoguciDodavanjeNalogaUTermin.addActionListener(actionListener);
    }

    public void DodajNalogUTerminAddActionListener(ActionListener actionListener) {
        btnDodajNalogUTermin.addActionListener(actionListener);
    }

    public void tabelaTerminiaddActionListener(MouseListener ml) {
        tblTermini.addMouseListener(ml);
    }

    public void otvorinalogAddActionListener(ActionListener actionListener) {
        btnUcitajNalogClana.addActionListener(actionListener);
    }

    public JToggleButton getBtnPretrazi() {
        return btnPretrazi;
    }

    public void setBtnPretrazi(JToggleButton btnPretrazi) {
        this.btnPretrazi = btnPretrazi;
    }

    public JComboBox<Object> getCbKriterijumPretrage() {
        return cbKriterijumPretrage;
    }

    public void setCbKriterijumPretrage(JComboBox<Object> cbKriterijumPretrage) {
        this.cbKriterijumPretrage = cbKriterijumPretrage;
    }

    public JTable getTblRezultati() {
        return tblRezultati;
    }

    public void setTblRezultati(JTable tblRezultati) {
        this.tblRezultati = tblRezultati;
    }

    public JTextField getTxtPretraziValue() {
        return txtPretraziValue;
    }

    public void setTxtPretraziValue(JTextField txtPretraziValue) {
        this.txtPretraziValue = txtPretraziValue;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnDodajNalogUTermin;
    private javax.swing.JToggleButton btnOmoguciDodavanjeNalogaUTermin;
    private javax.swing.JToggleButton btnPretrazi;
    private javax.swing.JToggleButton btnUcitajNalogClana;
    private javax.swing.JComboBox<Object> cbKriterijumPretrage;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblDatumTermina;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblLupa;
    private javax.swing.JLabel lblNoResaults;
    private javax.swing.JLabel lblPoCemuBiStePretrazili1;
    private javax.swing.JLabel lblPretraziNalogeClanova;
    private javax.swing.JLabel lblUlogovanTrener;
    private javax.swing.JLabel lblVremeKrajaTermina;
    private javax.swing.JLabel lblVremeKrajaTermina1;
    private javax.swing.JLabel lblVremePocetkaTermina;
    private javax.swing.JPanel panelPretraga;
    private javax.swing.JPanel panelPrisustvoTerminu;
    private javax.swing.JPanel panelRezultati;
    private javax.swing.JPanel panelTermini;
    private javax.swing.JTable tblPrisustva;
    private javax.swing.JTable tblRezultati;
    private javax.swing.JTable tblTermini;
    private javax.swing.JTextField txtDatumTermina;
    private javax.swing.JTextField txtKrajTermina;
    private javax.swing.JTextField txtPocetakTermina;
    private javax.swing.JTextField txtPretraziValue;
    private javax.swing.JTextField txtTrajanjee;
    private javax.swing.JTextField txtUlogovanTrener;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JLabel getLblNoResaults() {
        return lblNoResaults;
    }

    public void setLblNoResaults(javax.swing.JLabel lblNoResaults) {
        this.lblNoResaults = lblNoResaults;
    }

    public javax.swing.JToggleButton getBtnUcitajNalogClana() {
        return btnUcitajNalogClana;
    }

    public void setBtnUcitajNalogClana(javax.swing.JToggleButton btnUcitajNalogClana) {
        this.btnUcitajNalogClana = btnUcitajNalogClana;
    }

    public javax.swing.JToggleButton getBtnDodajNalogUTermin() {
        return btnDodajNalogUTermin;
    }

    public void setBtnDodajNalogUTermin(javax.swing.JToggleButton btnDodajNalogUTermin) {
        this.btnDodajNalogUTermin = btnDodajNalogUTermin;
    }

    public javax.swing.JToggleButton getBtnOmoguciDodavanjeNalogaUTermin() {
        return btnOmoguciDodavanjeNalogaUTermin;
    }

    public void setBtnOmoguciDodavanjeNalogaUTermin(javax.swing.JToggleButton btnOmoguciDodavanjeNalogaUTermin) {
        this.btnOmoguciDodavanjeNalogaUTermin = btnOmoguciDodavanjeNalogaUTermin;
    }

    public javax.swing.JTable getTblGrupe() {
        return tblPrisustva;
    }

    public void setTblGrupe(javax.swing.JTable tblGrupe) {
        this.tblPrisustva = tblGrupe;
    }

    public javax.swing.JTable getTblTermini() {
        return tblTermini;
    }

    public void setTblTermini(javax.swing.JTable tblTermini) {
        this.tblTermini = tblTermini;
    }

    public javax.swing.JTextField getTxtDatumTermina() {
        return txtDatumTermina;
    }

    public void setTxtDatumTermina(javax.swing.JTextField txtDatumTermina) {
        this.txtDatumTermina = txtDatumTermina;
    }

    public javax.swing.JTextField getTxtKrajTermina() {
        return txtKrajTermina;
    }

    public void setTxtKrajTermina(javax.swing.JTextField txtKrajTermina) {
        this.txtKrajTermina = txtKrajTermina;
    }

    public javax.swing.JTextField getTxtPocetakTermina() {
        return txtPocetakTermina;
    }

    public void setTxtPocetakTermina(javax.swing.JTextField txtPocetakTermina) {
        this.txtPocetakTermina = txtPocetakTermina;
    }

    public javax.swing.JTextField getTxtTrajanjee() {
        return txtTrajanjee;
    }

    public void setTxtTrajanjee(javax.swing.JTextField txtTrajanjee) {
        this.txtTrajanjee = txtTrajanjee;
    }

    public javax.swing.JTextField getTxtUlogovanTrener() {
        return txtUlogovanTrener;
    }

    public void setTxtUlogovanTrener(javax.swing.JTextField txtUlogovanTrener) {
        this.txtUlogovanTrener = txtUlogovanTrener;
    }

    public javax.swing.JLabel getLblError() {
        return lblError;
    }

    public void setLblError(javax.swing.JLabel lblError) {
        this.lblError = lblError;
    }

    public javax.swing.JTable getTblPrisustva() {
        return tblPrisustva;
    }

    public void setTblPrisustva(javax.swing.JTable tblPrisustva) {
        this.tblPrisustva = tblPrisustva;
    }
}
