/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view.forms;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;

/**
 *
 * @author Mr OLOGIZ
 */
public class FrmRegistrovanjeTermina extends javax.swing.JDialog {

    /**
     * Creates new form FrmRegistrovanjeTermina
     */
    public FrmRegistrovanjeTermina(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        lblDatum = new javax.swing.JLabel();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        lblVremePocetka = new javax.swing.JLabel();
        lblVremeKraja = new javax.swing.JLabel();
        lblTrajanje = new javax.swing.JLabel();
        lblErrorTermin = new javax.swing.JLabel();
        txtMaxBrojClanova = new javax.swing.JTextField();
        panelGrupe = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGrupe = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblNazivGrupe = new javax.swing.JLabel();
        txtNazivGrupe = new javax.swing.JTextField();
        lblBrojTermina = new javax.swing.JLabel();
        txtBrojTermina = new javax.swing.JTextField();
        btnDodajGrupu = new javax.swing.JButton();
        lblErrorDodavanjeGrupe = new javax.swing.JLabel();
        lblTrenerGrupe = new javax.swing.JLabel();
        txtTrenerIzabraneGrupe = new javax.swing.JTextField();
        lblSlobodneGrupe = new javax.swing.JLabel();
        btnZapamtiTermin = new javax.swing.JButton();
        panelSviTermini = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTermini = new javax.swing.JTable();
        lblDatumTermina = new javax.swing.JLabel();
        lblVremeKrajaTermina = new javax.swing.JLabel();
        txtDatumTermina = new javax.swing.JTextField();
        txtPocetakTermina = new javax.swing.JTextField();
        lblVremePocetkaTermina = new javax.swing.JLabel();
        txtKrajTermina = new javax.swing.JTextField();
        lblVremeKrajaTermina1 = new javax.swing.JLabel();
        txtTrajanjee = new javax.swing.JTextField();
        txtVremePocetka = new javax.swing.JTextField();
        txtTrajanje = new javax.swing.JTextField();
        txtVremeKraja1 = new javax.swing.JTextField();
        txtMaxBrClanova1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTerminiBezGrupa = new javax.swing.JTable();
        btnDodajTermineUGrupu = new javax.swing.JButton();
        btnOmoguciSK = new javax.swing.JButton();
        btnDodajTermnUTabelu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelBackground.setBackground(new java.awt.Color(0, 0, 0));
        panelBackground.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrovanje novog termina", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        lblDatum.setBackground(new java.awt.Color(0, 0, 0));
        lblDatum.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblDatum.setForeground(new java.awt.Color(255, 255, 255));
        lblDatum.setText("Datum:");

        dateChooserCombo1.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    dateChooserCombo1.setCalendarBackground(new java.awt.Color(0, 0, 0));
    dateChooserCombo1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED,
        (java.awt.Color)null,
        (java.awt.Color)null,
        (java.awt.Color)null,
        (java.awt.Color)null));
dateChooserCombo1.setCalendarPreferredSize(new java.awt.Dimension(250, 150));
dateChooserCombo1.setFieldFont(new java.awt.Font("Microsoft YaHei", java.awt.Font.PLAIN, 12));
dateChooserCombo1.setNavigateFont(new java.awt.Font("Microsoft YaHei", java.awt.Font.PLAIN, 12));

lblVremePocetka.setBackground(new java.awt.Color(0, 0, 0));
lblVremePocetka.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
lblVremePocetka.setForeground(new java.awt.Color(255, 255, 255));
lblVremePocetka.setText("Vreme početka:");

lblVremeKraja.setBackground(new java.awt.Color(0, 0, 0));
lblVremeKraja.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
lblVremeKraja.setForeground(new java.awt.Color(255, 255, 255));
lblVremeKraja.setText("Vreme kraja:");

lblTrajanje.setBackground(new java.awt.Color(0, 0, 0));
lblTrajanje.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
lblTrajanje.setForeground(new java.awt.Color(255, 255, 255));
lblTrajanje.setText("Trajanje:");

lblErrorTermin.setBackground(new java.awt.Color(0, 0, 0));
lblErrorTermin.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
lblErrorTermin.setForeground(new java.awt.Color(255, 0, 51));

txtMaxBrojClanova.setFont(new java.awt.Font("Microsoft YaHei", 0, 11)); // NOI18N

panelGrupe.setBackground(new java.awt.Color(0, 0, 0));
panelGrupe.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Grupe", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
panelGrupe.setForeground(new java.awt.Color(255, 255, 255));

tblGrupe.setBackground(new java.awt.Color(0, 0, 0));
tblGrupe.setFont(new java.awt.Font("Microsoft YaHei", 0, 11)); // NOI18N
tblGrupe.setForeground(new java.awt.Color(255, 255, 255));
tblGrupe.setModel(new javax.swing.table.DefaultTableModel(
    new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
    },
    new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
    }
    ));
    tblGrupe.setGridColor(new java.awt.Color(255, 255, 255));
    jScrollPane1.setViewportView(tblGrupe);

    jPanel1.setBackground(new java.awt.Color(0, 0, 0));
    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dodaj grupu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N

    lblNazivGrupe.setBackground(new java.awt.Color(0, 0, 0));
    lblNazivGrupe.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
    lblNazivGrupe.setForeground(new java.awt.Color(255, 255, 255));
    lblNazivGrupe.setText("Naziv grupe:");

    txtNazivGrupe.setFont(new java.awt.Font("Microsoft YaHei", 0, 11)); // NOI18N

    lblBrojTermina.setBackground(new java.awt.Color(0, 0, 0));
    lblBrojTermina.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
    lblBrojTermina.setForeground(new java.awt.Color(255, 255, 255));
    lblBrojTermina.setText("Broj termina:");

    txtBrojTermina.setFont(new java.awt.Font("Microsoft YaHei", 0, 11)); // NOI18N

    btnDodajGrupu.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
    btnDodajGrupu.setText("Dodaj grupu");
    btnDodajGrupu.setBorder(null);

    lblErrorDodavanjeGrupe.setBackground(new java.awt.Color(0, 0, 0));
    lblErrorDodavanjeGrupe.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
    lblErrorDodavanjeGrupe.setForeground(new java.awt.Color(255, 0, 51));

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblNazivGrupe)
                        .addComponent(lblBrojTermina))
                    .addGap(35, 35, 35)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNazivGrupe, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                        .addComponent(txtBrojTermina))
                    .addGap(37, 37, 37)
                    .addComponent(btnDodajGrupu, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(lblErrorDodavanjeGrupe)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNazivGrupe)
                    .addComponent(txtNazivGrupe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(btnDodajGrupu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblBrojTermina)
                .addComponent(txtBrojTermina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
            .addComponent(lblErrorDodavanjeGrupe)
            .addGap(30, 30, 30))
    );

    lblTrenerGrupe.setBackground(new java.awt.Color(0, 0, 0));
    lblTrenerGrupe.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
    lblTrenerGrupe.setForeground(new java.awt.Color(255, 255, 255));
    lblTrenerGrupe.setText("Ulogovan trener:");

    txtTrenerIzabraneGrupe.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
    txtTrenerIzabraneGrupe.setDisabledTextColor(new java.awt.Color(51, 51, 51));

    lblSlobodneGrupe.setBackground(new java.awt.Color(0, 0, 0));
    lblSlobodneGrupe.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
    lblSlobodneGrupe.setForeground(new java.awt.Color(255, 255, 255));
    lblSlobodneGrupe.setText("Slobodne grupe ulogovanog trenera:");

    javax.swing.GroupLayout panelGrupeLayout = new javax.swing.GroupLayout(panelGrupe);
    panelGrupe.setLayout(panelGrupeLayout);
    panelGrupeLayout.setHorizontalGroup(
        panelGrupeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panelGrupeLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(panelGrupeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                .addGroup(panelGrupeLayout.createSequentialGroup()
                    .addGroup(panelGrupeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblSlobodneGrupe)
                        .addGroup(panelGrupeLayout.createSequentialGroup()
                            .addComponent(lblTrenerGrupe)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtTrenerIzabraneGrupe, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
    );
    panelGrupeLayout.setVerticalGroup(
        panelGrupeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panelGrupeLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(panelGrupeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblTrenerGrupe)
                .addComponent(txtTrenerIzabraneGrupe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(24, 24, 24)
            .addComponent(lblSlobodneGrupe)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    btnZapamtiTermin.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
    btnZapamtiTermin.setText("Zapamti termin");
    btnZapamtiTermin.setBorder(null);

    panelSviTermini.setBackground(new java.awt.Color(0, 0, 0));
    panelSviTermini.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Svi termini", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
    panelSviTermini.setForeground(new java.awt.Color(255, 255, 255));

    tblTermini.setBackground(new java.awt.Color(0, 0, 0));
    tblTermini.setFont(new java.awt.Font("Microsoft YaHei", 0, 11)); // NOI18N
    tblTermini.setForeground(new java.awt.Color(255, 255, 255));
    tblTermini.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
        },
        new String [] {
            "Title 1", "Title 2", "Title 3", "Title 4"
        }
    ));
    tblTermini.setGridColor(new java.awt.Color(255, 255, 255));
    jScrollPane2.setViewportView(tblTermini);

    lblDatumTermina.setBackground(new java.awt.Color(0, 0, 0));
    lblDatumTermina.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
    lblDatumTermina.setForeground(new java.awt.Color(255, 255, 255));
    lblDatumTermina.setText("Datum termina (yyyy-mm-dd):");

    lblVremeKrajaTermina.setBackground(new java.awt.Color(0, 0, 0));
    lblVremeKrajaTermina.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
    lblVremeKrajaTermina.setForeground(new java.awt.Color(255, 255, 255));
    lblVremeKrajaTermina.setText("Vreme kraja termina:");

    txtDatumTermina.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
    txtDatumTermina.setDisabledTextColor(new java.awt.Color(51, 51, 51));

    txtPocetakTermina.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
    txtPocetakTermina.setDisabledTextColor(new java.awt.Color(51, 51, 51));

    lblVremePocetkaTermina.setBackground(new java.awt.Color(0, 0, 0));
    lblVremePocetkaTermina.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
    lblVremePocetkaTermina.setForeground(new java.awt.Color(255, 255, 255));
    lblVremePocetkaTermina.setText("Vreme početka termina:");

    txtKrajTermina.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
    txtKrajTermina.setDisabledTextColor(new java.awt.Color(51, 51, 51));

    lblVremeKrajaTermina1.setBackground(new java.awt.Color(0, 0, 0));
    lblVremeKrajaTermina1.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
    lblVremeKrajaTermina1.setForeground(new java.awt.Color(255, 255, 255));
    lblVremeKrajaTermina1.setText("Trajanje:");

    txtTrajanjee.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
    txtTrajanjee.setDisabledTextColor(new java.awt.Color(51, 51, 51));

    javax.swing.GroupLayout panelSviTerminiLayout = new javax.swing.GroupLayout(panelSviTermini);
    panelSviTermini.setLayout(panelSviTerminiLayout);
    panelSviTerminiLayout.setHorizontalGroup(
        panelSviTerminiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panelSviTerminiLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(panelSviTerminiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSviTerminiLayout.createSequentialGroup()
                    .addGroup(panelSviTerminiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblVremePocetkaTermina)
                        .addComponent(lblDatumTermina))
                    .addGap(18, 18, 18)
                    .addGroup(panelSviTerminiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtPocetakTermina, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addComponent(txtDatumTermina))
                    .addGap(47, 47, 47)
                    .addComponent(lblVremeKrajaTermina)
                    .addGap(18, 18, 18)
                    .addComponent(txtKrajTermina, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(63, 63, 63)
                    .addComponent(lblVremeKrajaTermina1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(txtTrajanjee, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)))
            .addContainerGap())
    );
    panelSviTerminiLayout.setVerticalGroup(
        panelSviTerminiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panelSviTerminiLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(panelSviTerminiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblDatumTermina)
                .addComponent(txtDatumTermina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(panelSviTerminiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblVremeKrajaTermina)
                .addComponent(txtPocetakTermina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblVremePocetkaTermina)
                .addComponent(txtKrajTermina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblVremeKrajaTermina1)
                .addComponent(txtTrajanjee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(13, Short.MAX_VALUE))
    );

    txtVremePocetka.setFont(new java.awt.Font("Microsoft YaHei", 0, 11)); // NOI18N

    txtTrajanje.setFont(new java.awt.Font("Microsoft YaHei", 0, 11)); // NOI18N

    txtVremeKraja1.setFont(new java.awt.Font("Microsoft YaHei", 0, 11)); // NOI18N

    txtMaxBrClanova1.setBackground(new java.awt.Color(0, 0, 0));
    txtMaxBrClanova1.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
    txtMaxBrClanova1.setForeground(new java.awt.Color(255, 255, 255));
    txtMaxBrClanova1.setText("Maksimalni broj članova:");

    jPanel2.setBackground(new java.awt.Color(0, 0, 0));
    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Termini bez grupe", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

    tblTerminiBezGrupa.setBackground(new java.awt.Color(0, 0, 0));
    tblTerminiBezGrupa.setFont(new java.awt.Font("Microsoft YaHei", 0, 11)); // NOI18N
    tblTerminiBezGrupa.setForeground(new java.awt.Color(255, 255, 255));
    tblTerminiBezGrupa.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
        },
        new String [] {
            "Title 1", "Title 2", "Title 3", "Title 4"
        }
    ));
    tblTerminiBezGrupa.setGridColor(new java.awt.Color(255, 255, 255));
    jScrollPane3.setViewportView(tblTerminiBezGrupa);

    btnDodajTermineUGrupu.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
    btnDodajTermineUGrupu.setText("Dodaj termine u grupu");
    btnDodajTermineUGrupu.setBorder(null);

    btnOmoguciSK.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
    btnOmoguciSK.setText("Omogući SK");
    btnOmoguciSK.setBorder(null);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnOmoguciSK, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btnDodajTermineUGrupu, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(24, 24, 24))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnDodajTermineUGrupu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnOmoguciSK, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(22, Short.MAX_VALUE))
    );

    btnDodajTermnUTabelu.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
    btnDodajTermnUTabelu.setText("Dodaj termin u tabelu");
    btnDodajTermnUTabelu.setBorder(null);

    javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
    panelBackground.setLayout(panelBackgroundLayout);
    panelBackgroundLayout.setHorizontalGroup(
        panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panelBackgroundLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelSviTermini, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelBackgroundLayout.createSequentialGroup()
                    .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                            .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(panelBackgroundLayout.createSequentialGroup()
                                    .addComponent(lblDatum)
                                    .addGap(130, 130, 130)
                                    .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(txtVremePocetka)))
                                .addComponent(lblVremePocetka)
                                .addGroup(panelBackgroundLayout.createSequentialGroup()
                                    .addComponent(lblVremeKraja)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtVremeKraja1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelBackgroundLayout.createSequentialGroup()
                                    .addComponent(lblTrajanje)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTrajanje, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelBackgroundLayout.createSequentialGroup()
                                    .addComponent(btnZapamtiTermin, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDodajTermnUTabelu, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelBackgroundLayout.createSequentialGroup()
                                    .addComponent(txtMaxBrClanova1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                    .addComponent(txtMaxBrojClanova, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(24, 24, 24)
                            .addComponent(lblErrorTermin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(18, 18, 18)
                    .addComponent(panelGrupe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
    );
    panelBackgroundLayout.setVerticalGroup(
        panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panelBackgroundLayout.createSequentialGroup()
            .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(panelBackgroundLayout.createSequentialGroup()
                    .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDatum))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblVremePocetka)
                        .addComponent(txtVremePocetka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtVremeKraja1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblVremeKraja))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTrajanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTrajanje))
                    .addGap(18, 18, 18)
                    .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMaxBrClanova1)
                        .addComponent(txtMaxBrojClanova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnZapamtiTermin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnDodajTermnUTabelu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackgroundLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblErrorTermin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(panelGrupe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(panelSviTermini, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(panelBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajGrupu;
    private javax.swing.JButton btnDodajTermineUGrupu;
    private javax.swing.JButton btnDodajTermnUTabelu;
    private javax.swing.JButton btnOmoguciSK;
    private javax.swing.JButton btnZapamtiTermin;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblBrojTermina;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JLabel lblDatumTermina;
    private javax.swing.JLabel lblErrorDodavanjeGrupe;
    private javax.swing.JLabel lblErrorTermin;
    private javax.swing.JLabel lblNazivGrupe;
    private javax.swing.JLabel lblSlobodneGrupe;
    private javax.swing.JLabel lblTrajanje;
    private javax.swing.JLabel lblTrenerGrupe;
    private javax.swing.JLabel lblVremeKraja;
    private javax.swing.JLabel lblVremeKrajaTermina;
    private javax.swing.JLabel lblVremeKrajaTermina1;
    private javax.swing.JLabel lblVremePocetka;
    private javax.swing.JLabel lblVremePocetkaTermina;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelGrupe;
    private javax.swing.JPanel panelSviTermini;
    private javax.swing.JTable tblGrupe;
    private javax.swing.JTable tblTermini;
    private javax.swing.JTable tblTerminiBezGrupa;
    private javax.swing.JTextField txtBrojTermina;
    private javax.swing.JTextField txtDatumTermina;
    private javax.swing.JTextField txtKrajTermina;
    private javax.swing.JLabel txtMaxBrClanova1;
    private javax.swing.JTextField txtMaxBrojClanova;
    private javax.swing.JTextField txtNazivGrupe;
    private javax.swing.JTextField txtPocetakTermina;
    private javax.swing.JTextField txtTrajanje;
    private javax.swing.JTextField txtTrajanjee;
    private javax.swing.JTextField txtTrenerIzabraneGrupe;
    private javax.swing.JTextField txtVremeKraja1;
    private javax.swing.JTextField txtVremePocetka;
    // End of variables declaration//GEN-END:variables

    public void btnOmoguciAddActionListener(ActionListener al) {
        btnOmoguciSK.addActionListener(al);
    }

    public void btnDodajUTabeluTerminAddActionListener(ActionListener al) {
        btnDodajTermnUTabelu.addActionListener(al);
    }

    public void btnDodajSveTermineZaJednuGrupuAddActionListener(ActionListener al) {
        btnDodajTermineUGrupu.addActionListener(al);
    }

    public void dodavanjeGrupeAddActionListener(ActionListener actionListener) {
        btnDodajGrupu.addActionListener(actionListener);
    }

    public void dodavanjeTerminaAddActionListener(ActionListener actionListener) {
        btnZapamtiTermin.addActionListener(actionListener);
    }

    public void klikNatTabeluTerminaActionListener(MouseListener actionListener) {
        tblTermini.addMouseListener(actionListener);
    }

    public javax.swing.JButton getBtnDodajGrupu() {
        return btnDodajGrupu;
    }

    public void setBtnDodajGrupu(javax.swing.JButton btnDodajGrupu) {
        this.btnDodajGrupu = btnDodajGrupu;
    }

    public javax.swing.JButton getBtnZapamtiTermin() {
        return btnZapamtiTermin;
    }

    public void setBtnZapamtiTermin(javax.swing.JButton btnZapamtiTermin) {
        this.btnZapamtiTermin = btnZapamtiTermin;
    }

    public datechooser.beans.DateChooserCombo getDateChooserCombo1() {
        return dateChooserCombo1;
    }

    public void setDateChooserCombo1(datechooser.beans.DateChooserCombo dateChooserCombo1) {
        this.dateChooserCombo1 = dateChooserCombo1;
    }

    public javax.swing.JTable getTblGrupe() {
        return tblGrupe;
    }

    public void setTblGrupe(javax.swing.JTable tblGrupe) {
        this.tblGrupe = tblGrupe;
    }

    public javax.swing.JTextField getTxtBrojTermina() {
        return txtBrojTermina;
    }

    public void setTxtBrojTermina(javax.swing.JTextField txtBrojTermina) {
        this.txtBrojTermina = txtBrojTermina;
    }

    public javax.swing.JLabel getTxtMaxBrClanova() {
        return lblErrorTermin;
    }

    public void setTxtMaxBrClanova(javax.swing.JLabel txtMaxBrClanova) {
        this.lblErrorTermin = txtMaxBrClanova;
    }

    public javax.swing.JTextField getTxtMaxBrojClanova() {
        return txtMaxBrojClanova;
    }

    public void setTxtMaxBrojClanova(javax.swing.JTextField txtMaxBrojClanova) {
        this.txtMaxBrojClanova = txtMaxBrojClanova;
    }

    public javax.swing.JTextField getTxtNazivGrupe() {
        return txtNazivGrupe;
    }

    public void setTxtNazivGrupe(javax.swing.JTextField txtNazivGrupe) {
        this.txtNazivGrupe = txtNazivGrupe;
    }

    public javax.swing.JTextField getTxtTrajanje() {
        return txtTrajanje;
    }

    public void setTxtTrajanje(javax.swing.JTextField txtTrajanje) {
        this.txtTrajanje = txtTrajanje;
    }

    public javax.swing.JTextField getTxtTrenerIzabraneGrupe() {
        return txtTrenerIzabraneGrupe;
    }

    public void setTxtTrenerIzabraneGrupe(javax.swing.JTextField txtTrenerIzabraneGrupe) {
        this.txtTrenerIzabraneGrupe = txtTrenerIzabraneGrupe;
    }

    public void setTxtVremeKraja(javax.swing.JFormattedTextField txtVremeKraja) {
        this.txtTrajanje = txtVremeKraja;
    }

    public void setTxtVremePocetka(javax.swing.JFormattedTextField txtVremePocetka) {
        this.txtVremePocetka = txtVremePocetka;
    }

    public javax.swing.JLabel getLblErrorDodavanjeGrupe() {
        return lblErrorDodavanjeGrupe;
    }

    public void setLblErrorDodavanjeGrupe(javax.swing.JLabel lblErrorDodavanjeGrupe) {
        this.lblErrorDodavanjeGrupe = lblErrorDodavanjeGrupe;
    }

    public javax.swing.JTable getTblTermini() {
        return tblTermini;
    }

    public void setTblTermini(javax.swing.JTable tblTermini) {
        this.tblTermini = tblTermini;
    }

    public javax.swing.JTextField getTxtDatumTermina() {
        return txtDatumTermina;
    }

    public void setTxtDatumTermina(javax.swing.JTextField txtDatumTermina) {
        this.txtDatumTermina = txtDatumTermina;
    }

    public javax.swing.JTextField getTxtKrajTermina() {
        return txtKrajTermina;
    }

    public void setTxtKrajTermina(javax.swing.JTextField txtKrajTermina) {
        this.txtKrajTermina = txtKrajTermina;
    }

    public javax.swing.JTextField getTxtPocetakTermina() {
        return txtPocetakTermina;
    }

    public void setTxtPocetakTermina(javax.swing.JTextField txtPocetakTermina) {
        this.txtPocetakTermina = txtPocetakTermina;
    }

    public javax.swing.JTextField getTxtTrajanjee() {
        return txtTrajanjee;
    }

    public void setTxtTrajanjee(javax.swing.JTextField txtTrajanjee) {
        this.txtTrajanjee = txtTrajanjee;
    }

    public javax.swing.JTextField getTxtVremeKraja1() {
        return txtVremeKraja1;
    }

    public void setTxtVremeKraja1(javax.swing.JTextField txtVremeKraja1) {
        this.txtVremeKraja1 = txtVremeKraja1;
    }

    public javax.swing.JTextField getTxtVremePocetka() {
        return txtVremePocetka;
    }

    public void setTxtVremePocetka(javax.swing.JTextField txtVremePocetka) {
        this.txtVremePocetka = txtVremePocetka;
    }

    public javax.swing.JLabel getLblErrorTermin() {
        return lblErrorTermin;
    }

    public void setLblErrorTermin(javax.swing.JLabel lblErrorTermin) {
        this.lblErrorTermin = lblErrorTermin;
    }

    public javax.swing.JButton getBtnDodajTermineUGrupu() {
        return btnDodajTermineUGrupu;
    }

    public void setBtnDodajTermineUGrupu(javax.swing.JButton btnDodajTermineUGrupu) {
        this.btnDodajTermineUGrupu = btnDodajTermineUGrupu;
    }

    public javax.swing.JTable getTblTerminiBezGrupa() {
        return tblTerminiBezGrupa;
    }

    public void setTblTerminiBezGrupa(javax.swing.JTable tblTerminiBezGrupa) {
        this.tblTerminiBezGrupa = tblTerminiBezGrupa;
    }

    public javax.swing.JButton getBtnOmoguciSK() {
        return btnOmoguciSK;
    }

    public void setBtnOmoguciSK(javax.swing.JButton btnOmoguciSK) {
        this.btnOmoguciSK = btnOmoguciSK;
    }

    public javax.swing.JButton getBtnDodajTermnUTabelu() {
        return btnDodajTermnUTabelu;
    }

    public void setBtnDodajTermnUTabelu(javax.swing.JButton btnDodajTermnUTabelu) {
        this.btnDodajTermnUTabelu = btnDodajTermnUTabelu;
    }
}
