/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view.forms;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;

/**
 *
 * @author Mr OLOGIZ
 */
public class FrmTerminCRUD extends javax.swing.JDialog {

    /**
     * Creates new form FrmTerminCRUD
     */
    public FrmTerminCRUD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackGround = new javax.swing.JPanel();
        lblidTermina = new javax.swing.JLabel();
        lblDatum = new javax.swing.JLabel();
        lblvremePocetka = new javax.swing.JLabel();
        lblVremeKraja = new javax.swing.JLabel();
        lbTrajanje = new javax.swing.JLabel();
        lblBrojClanova = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtVremePocetka = new javax.swing.JTextField();
        txtTrajanje = new javax.swing.JTextField();
        txtVremeKraja = new javax.swing.JTextField();
        lblMaxBrojClanova = new javax.swing.JLabel();
        btnObrisiTermin = new javax.swing.JButton();
        btnPotvrdiIzmene = new javax.swing.JButton();
        btnOmoguciIzmene = new javax.swing.JButton();
        lblErrorMessage = new javax.swing.JLabel();
        txtBrojClanova = new javax.swing.JTextField();
        txtMaxBrClanova = new javax.swing.JTextField();
        lblGrupaTermina = new javax.swing.JLabel();
        txtGrupaa = new javax.swing.JTextField();
        panelGrupe = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGrupe = new javax.swing.JTable();
        lblUlogovanTrener = new javax.swing.JLabel();
        txtUlogovanTrener = new javax.swing.JTextField();
        txtDatum = new javax.swing.JTextField();
        panelDatum = new javax.swing.JPanel();
        dateChooser = new datechooser.beans.DateChooserCombo();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelBackGround.setBackground(new java.awt.Color(0, 0, 0));

        lblidTermina.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblidTermina.setForeground(new java.awt.Color(255, 255, 255));
        lblidTermina.setText("id:");

        lblDatum.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblDatum.setForeground(new java.awt.Color(255, 255, 255));
        lblDatum.setText("datum:");

        lblvremePocetka.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblvremePocetka.setForeground(new java.awt.Color(255, 255, 255));
        lblvremePocetka.setText("vreme početka:");

        lblVremeKraja.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblVremeKraja.setForeground(new java.awt.Color(255, 255, 255));
        lblVremeKraja.setText("vreme kraja:");

        lbTrajanje.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lbTrajanje.setForeground(new java.awt.Color(255, 255, 255));
        lbTrajanje.setText("trajanje:");

        lblBrojClanova.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblBrojClanova.setForeground(new java.awt.Color(255, 255, 255));
        lblBrojClanova.setText("broj članova:");

        txtId.setBackground(new java.awt.Color(0, 0, 0));
        txtId.setForeground(new java.awt.Color(255, 255, 255));
        txtId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        txtVremePocetka.setBackground(new java.awt.Color(0, 0, 0));
        txtVremePocetka.setForeground(new java.awt.Color(255, 255, 255));
        txtVremePocetka.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        txtTrajanje.setBackground(new java.awt.Color(0, 0, 0));
        txtTrajanje.setForeground(new java.awt.Color(255, 255, 255));
        txtTrajanje.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        txtVremeKraja.setBackground(new java.awt.Color(0, 0, 0));
        txtVremeKraja.setForeground(new java.awt.Color(255, 255, 255));
        txtVremeKraja.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblMaxBrojClanova.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblMaxBrojClanova.setForeground(new java.awt.Color(255, 255, 255));
        lblMaxBrojClanova.setText("maksimalan broj članova:");

        btnObrisiTermin.setBackground(new java.awt.Color(255, 255, 255));
        btnObrisiTermin.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        btnObrisiTermin.setText("Obriši termin");

        btnPotvrdiIzmene.setBackground(new java.awt.Color(255, 255, 255));
        btnPotvrdiIzmene.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        btnPotvrdiIzmene.setText("Potvrdi promene");

        btnOmoguciIzmene.setBackground(new java.awt.Color(255, 255, 255));
        btnOmoguciIzmene.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        btnOmoguciIzmene.setText("Omogući promene");

        lblErrorMessage.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblErrorMessage.setForeground(new java.awt.Color(255, 0, 51));

        txtBrojClanova.setBackground(new java.awt.Color(0, 0, 0));
        txtBrojClanova.setForeground(new java.awt.Color(255, 255, 255));
        txtBrojClanova.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        txtMaxBrClanova.setBackground(new java.awt.Color(0, 0, 0));
        txtMaxBrClanova.setForeground(new java.awt.Color(255, 255, 255));
        txtMaxBrClanova.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblGrupaTermina.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblGrupaTermina.setForeground(new java.awt.Color(255, 255, 255));
        lblGrupaTermina.setText("Grupa termina:");

        txtGrupaa.setBackground(new java.awt.Color(0, 0, 0));
        txtGrupaa.setForeground(new java.awt.Color(255, 255, 255));
        txtGrupaa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        panelGrupe.setBackground(new java.awt.Color(0, 0, 0));
        panelGrupe.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Grupe ulogovanog trenera", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        panelGrupe.setOpaque(false);

        tblGrupe.setBackground(new java.awt.Color(0, 0, 0));
        tblGrupe.setFont(new java.awt.Font("Microsoft YaHei", 0, 11)); // NOI18N
        tblGrupe.setForeground(new java.awt.Color(255, 255, 255));
        tblGrupe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblGrupe.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tblGrupe);

        lblUlogovanTrener.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblUlogovanTrener.setForeground(new java.awt.Color(255, 255, 255));
        lblUlogovanTrener.setText("Ulogovan trener:");

        txtUlogovanTrener.setBackground(new java.awt.Color(0, 0, 0));
        txtUlogovanTrener.setForeground(new java.awt.Color(255, 255, 255));
        txtUlogovanTrener.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout panelGrupeLayout = new javax.swing.GroupLayout(panelGrupe);
        panelGrupe.setLayout(panelGrupeLayout);
        panelGrupeLayout.setHorizontalGroup(
            panelGrupeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGrupeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGrupeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                    .addGroup(panelGrupeLayout.createSequentialGroup()
                        .addComponent(lblUlogovanTrener)
                        .addGap(82, 82, 82)
                        .addComponent(txtUlogovanTrener, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelGrupeLayout.setVerticalGroup(
            panelGrupeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGrupeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGrupeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUlogovanTrener)
                    .addComponent(txtUlogovanTrener, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtDatum.setBackground(new java.awt.Color(0, 0, 0));
        txtDatum.setForeground(new java.awt.Color(255, 255, 255));
        txtDatum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        panelDatum.setBackground(new java.awt.Color(0, 0, 0));
        panelDatum.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "unesiDatum", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        dateChooser.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    dateChooser.setCalendarBackground(new java.awt.Color(0, 0, 0));
    dateChooser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED,
        (java.awt.Color)null,
        (java.awt.Color)null,
        (java.awt.Color)null,
        (java.awt.Color)null));
dateChooser.setCalendarPreferredSize(new java.awt.Dimension(250, 150));
dateChooser.setFieldFont(new java.awt.Font("Microsoft YaHei", java.awt.Font.PLAIN, 12));
dateChooser.setNavigateFont(new java.awt.Font("Microsoft YaHei", java.awt.Font.PLAIN, 12));

javax.swing.GroupLayout panelDatumLayout = new javax.swing.GroupLayout(panelDatum);
panelDatum.setLayout(panelDatumLayout);
panelDatumLayout.setHorizontalGroup(
    panelDatumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatumLayout.createSequentialGroup()
        .addGap(0, 8, Short.MAX_VALUE)
        .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    panelDatumLayout.setVerticalGroup(
        panelDatumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panelDatumLayout.createSequentialGroup()
            .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 21, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout panelBackGroundLayout = new javax.swing.GroupLayout(panelBackGround);
    panelBackGround.setLayout(panelBackGroundLayout);
    panelBackGroundLayout.setHorizontalGroup(
        panelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panelBackGroundLayout.createSequentialGroup()
            .addGap(10, 10, 10)
            .addGroup(panelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelGrupe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblidTermina)
                .addComponent(lblErrorMessage)
                .addGroup(panelBackGroundLayout.createSequentialGroup()
                    .addGroup(panelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelBackGroundLayout.createSequentialGroup()
                                .addGroup(panelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMaxBrojClanova)
                                    .addComponent(lblGrupaTermina)
                                    .addComponent(lblBrojClanova)
                                    .addComponent(lbTrajanje)
                                    .addComponent(lblVremeKraja)
                                    .addComponent(lblvremePocetka))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtVremePocetka, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVremeKraja, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTrajanje, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBrojClanova, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGrupaa, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaxBrClanova, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblDatum)
                        .addComponent(panelDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(29, 29, 29)
                    .addGroup(panelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnPotvrdiIzmene, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnOmoguciIzmene, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnObrisiTermin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    panelBackGroundLayout.setVerticalGroup(
        panelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panelBackGroundLayout.createSequentialGroup()
            .addGroup(panelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelBackGroundLayout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(lblidTermina))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackGroundLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnOmoguciIzmene, javax.swing.GroupLayout.Alignment.TRAILING))))
            .addGroup(panelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelBackGroundLayout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addGroup(panelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblDatum)
                        .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(panelDatum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(13, 13, 13)
                    .addGroup(panelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblvremePocetka)
                        .addComponent(txtVremePocetka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(panelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblVremeKraja)
                        .addComponent(txtVremeKraja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(panelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbTrajanje)
                        .addComponent(txtTrajanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(panelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBrojClanova)
                        .addComponent(txtBrojClanova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(panelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMaxBrojClanova)
                        .addComponent(txtMaxBrClanova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(panelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblGrupaTermina)
                        .addComponent(txtGrupaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(25, 25, 25)
                    .addComponent(lblErrorMessage)
                    .addGap(294, 294, 294))
                .addGroup(panelBackGroundLayout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(btnObrisiTermin)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btnPotvrdiIzmene)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelGrupe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(panelBackGround, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(panelBackGround, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnObrisiTermin;
    private javax.swing.JButton btnOmoguciIzmene;
    private javax.swing.JButton btnPotvrdiIzmene;
    private datechooser.beans.DateChooserCombo dateChooser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTrajanje;
    private javax.swing.JLabel lblBrojClanova;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JLabel lblErrorMessage;
    private javax.swing.JLabel lblGrupaTermina;
    private javax.swing.JLabel lblMaxBrojClanova;
    private javax.swing.JLabel lblUlogovanTrener;
    private javax.swing.JLabel lblVremeKraja;
    private javax.swing.JLabel lblidTermina;
    private javax.swing.JLabel lblvremePocetka;
    private javax.swing.JPanel panelBackGround;
    private javax.swing.JPanel panelDatum;
    private javax.swing.JPanel panelGrupe;
    private javax.swing.JTable tblGrupe;
    private javax.swing.JTextField txtBrojClanova;
    private javax.swing.JTextField txtDatum;
    private javax.swing.JTextField txtGrupaa;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMaxBrClanova;
    private javax.swing.JTextField txtTrajanje;
    private javax.swing.JTextField txtUlogovanTrener;
    private javax.swing.JTextField txtVremeKraja;
    private javax.swing.JTextField txtVremePocetka;
    // End of variables declaration//GEN-END:variables

    public void klikNaTabeluAddActionListener(MouseListener ml){
        tblGrupe.addMouseListener(ml);
    }
    
    public void OmoguciIzmeneTerminaAddActionListener(ActionListener actionListener) {
        btnOmoguciIzmene.addActionListener(actionListener);
    }
    
    public void ObrisiTerminAddActionListener(ActionListener actionListener) {
        btnObrisiTermin.addActionListener(actionListener);
    }
    
    public void IzmeniTerminAddActionListener(ActionListener actionListener) {
        btnPotvrdiIzmene.addActionListener(actionListener);
    }
       
    public javax.swing.JButton getBtnObrisiTermin() {
        return btnObrisiTermin;
    }
    
    
    
    public void setBtnObrisiTermin(javax.swing.JButton btnObrisiTermin) {
        this.btnObrisiTermin = btnObrisiTermin;
    }

    public javax.swing.JButton getBtnOmoguciIzmene() {
        return btnOmoguciIzmene;
    }

    public void setBtnOmoguciIzmene(javax.swing.JButton btnOmoguciIzmene) {
        this.btnOmoguciIzmene = btnOmoguciIzmene;
    }

    public javax.swing.JButton getBtnPotvrdiIzmene() {
        return btnPotvrdiIzmene;
    }

    public void setBtnPotvrdiIzmene(javax.swing.JButton btnPotvrdiIzmene) {
        this.btnPotvrdiIzmene = btnPotvrdiIzmene;
    }

  

    public javax.swing.JLabel getLblErrorMessage() {
        return lblErrorMessage;
    }

    public void setLblErrorMessage(javax.swing.JLabel lblErrorMessage) {
        this.lblErrorMessage = lblErrorMessage;
    }

    public javax.swing.JTextField getTxtBrojClanova() {
        return txtBrojClanova;
    }

    public void setTxtBrojClanova(javax.swing.JTextField txtBrojClanova) {
        this.txtBrojClanova = txtBrojClanova;
    }

    public javax.swing.JTextField getTxtGrupaTermina() {
        return txtUlogovanTrener;
    }

    public void setTxtGrupaTermina(javax.swing.JTextField txtGrupaTermina) {
        this.txtUlogovanTrener = txtGrupaTermina;
    }

    public javax.swing.JTextField getTxtId() {
        return txtId;
    }

    public void setTxtId(javax.swing.JTextField txtId) {
        this.txtId = txtId;
    }

    public javax.swing.JTextField getTxtMaxBrClanova() {
        return txtMaxBrClanova;
    }

    public void setTxtMaxBrClanova(javax.swing.JTextField txtMaxBrClanova) {
        this.txtMaxBrClanova = txtMaxBrClanova;
    }

    public javax.swing.JTextField getTxtTrajanje() {
        return txtTrajanje;
    }

    public void setTxtTrajanje(javax.swing.JTextField txtTrajanje) {
        this.txtTrajanje = txtTrajanje;
    }

    public javax.swing.JTextField getTxtVremeKraja() {
        return txtVremeKraja;
    }

    public void setTxtVremeKraja(javax.swing.JTextField txtVremeKraja) {
        this.txtVremeKraja = txtVremeKraja;
    }

    public javax.swing.JTextField getTxtVremePocetka() {
        return txtVremePocetka;
    }

    public void setTxtVremePocetka(javax.swing.JTextField txtVremePocetka) {
        this.txtVremePocetka = txtVremePocetka;
    }

    public javax.swing.JTable getTblGrupe() {
        return tblGrupe;
    }

    public void setTblGrupe(javax.swing.JTable tblGrupe) {
        this.tblGrupe = tblGrupe;
    }

    public javax.swing.JTextField getTxtUlogovanTrener() {
        return txtUlogovanTrener;
    }

    public void setTxtUlogovanTrener(javax.swing.JTextField txtUlogovanTrener) {
        this.txtUlogovanTrener = txtUlogovanTrener;
    }

    public javax.swing.JTextField getTxtGrupaa() {
        return txtGrupaa;
    }

    public void setTxtGrupaa(javax.swing.JTextField txtGrupaa) {
        this.txtGrupaa = txtGrupaa;
    }

    public javax.swing.JTextField getTxtDatum() {
        return txtDatum;
    }

    public void setTxtDatum(javax.swing.JTextField txtDatum) {
        this.txtDatum = txtDatum;
    }

    public datechooser.beans.DateChooserCombo getDateChooser() {
        return dateChooser;
    }

    public void setDateChooser(datechooser.beans.DateChooserCombo dateChooser) {
        this.dateChooser = dateChooser;
    }

    public javax.swing.JPanel getPanelDatum() {
        return panelDatum;
    }

    public void setPanelDatum(javax.swing.JPanel panelDatum) {
        this.panelDatum = panelDatum;
    }
}
