/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view.forms;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;

/**
 *
 * @author Mr OLOGIZ
 */
public class FrmClientManagement extends javax.swing.JDialog {

    /**
     * Creates new form FrmClientManagement
     */
    public FrmClientManagement(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        panelUlogovaniTreneri = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUlogovaniTreneri = new javax.swing.JTable();
        lblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelBackground.setBackground(new java.awt.Color(0, 0, 0));

        panelUlogovaniTreneri.setBackground(new java.awt.Color(0, 0, 0));
        panelUlogovaniTreneri.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ulogovani treneri", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        tblUlogovaniTreneri.setBackground(new java.awt.Color(0, 0, 0));
        tblUlogovaniTreneri.setFont(new java.awt.Font("Microsoft YaHei", 0, 11)); // NOI18N
        tblUlogovaniTreneri.setForeground(new java.awt.Color(255, 255, 255));
        tblUlogovaniTreneri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUlogovaniTreneri.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tblUlogovaniTreneri);

        javax.swing.GroupLayout panelUlogovaniTreneriLayout = new javax.swing.GroupLayout(panelUlogovaniTreneri);
        panelUlogovaniTreneri.setLayout(panelUlogovaniTreneriLayout);
        panelUlogovaniTreneriLayout.setHorizontalGroup(
            panelUlogovaniTreneriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 732, Short.MAX_VALUE)
            .addGroup(panelUlogovaniTreneriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelUlogovaniTreneriLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 927, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelUlogovaniTreneriLayout.setVerticalGroup(
            panelUlogovaniTreneriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
            .addGroup(panelUlogovaniTreneriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelUlogovaniTreneriLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        lblError.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelUlogovaniTreneri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addComponent(lblError)
                        .addGap(0, 959, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panelUlogovaniTreneri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(lblError)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblError;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelUlogovaniTreneri;
    private javax.swing.JTable tblUlogovaniTreneri;
    // End of variables declaration//GEN-END:variables


    public javax.swing.JLabel getLblError() {
        return lblError;
    }

    public void setLblError(javax.swing.JLabel lblError) {
        this.lblError = lblError;
    }

    public javax.swing.JTable getTblUlogovaniTreneri() {
        return tblUlogovaniTreneri;
    }

    public void setTblUlogovaniTreneri(javax.swing.JTable tblUlogovaniTreneri) {
        this.tblUlogovaniTreneri = tblUlogovaniTreneri;
    }
}
