/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view.forms;

import java.awt.event.ActionListener;

/**
 *
 * @author Mr OLOGIZ
 */
public class FrmServerConnectionForm extends javax.swing.JFrame {

    /**
     * Creates new form FrmServerConnectionForm
     */
    public FrmServerConnectionForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        panelServerConfig = new javax.swing.JPanel();
        lblPort = new javax.swing.JLabel();
        txtPortServer = new javax.swing.JTextField();
        lblPort1 = new javax.swing.JLabel();
        txtServerStatus = new javax.swing.JTextField();
        lblServerIcon = new javax.swing.JLabel();
        panelServerConfig1 = new javax.swing.JPanel();
        lblDbUrl = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUrlDatabase = new javax.swing.JTextField();
        txtUserDatabase = new javax.swing.JTextField();
        txtPasswordDB = new javax.swing.JPasswordField();
        lblDBIcon = new javax.swing.JLabel();
        btnPokreniServer = new javax.swing.JButton();
        btnZaustaviServer = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuKlijent = new javax.swing.JMenu();
        miUpravljanje = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBackground.setBackground(new java.awt.Color(0, 0, 0));

        panelServerConfig.setBackground(new java.awt.Color(0, 0, 0));
        panelServerConfig.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Konfiguracija servera", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        lblPort.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        lblPort.setForeground(new java.awt.Color(255, 255, 255));
        lblPort.setText("port:");

        txtPortServer.setFont(new java.awt.Font("Microsoft YaHei", 2, 12)); // NOI18N
        txtPortServer.setDisabledTextColor(new java.awt.Color(102, 102, 102));

        lblPort1.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        lblPort1.setForeground(new java.awt.Color(255, 255, 255));
        lblPort1.setText("Server status:");

        txtServerStatus.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        txtServerStatus.setDisabledTextColor(new java.awt.Color(102, 102, 102));

        lblServerIcon.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        lblServerIcon.setForeground(new java.awt.Color(255, 255, 255));
        lblServerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/ac/bg/fon/ps/images/serverIcon.png"))); // NOI18N

        javax.swing.GroupLayout panelServerConfigLayout = new javax.swing.GroupLayout(panelServerConfig);
        panelServerConfig.setLayout(panelServerConfigLayout);
        panelServerConfigLayout.setHorizontalGroup(
            panelServerConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelServerConfigLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelServerConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPort)
                    .addComponent(lblPort1))
                .addGap(26, 26, 26)
                .addGroup(panelServerConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPortServer, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtServerStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(lblServerIcon)
                .addGap(41, 41, 41))
        );
        panelServerConfigLayout.setVerticalGroup(
            panelServerConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelServerConfigLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelServerConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPortServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPort))
                .addGap(18, 18, 18)
                .addGroup(panelServerConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPort1)
                    .addComponent(txtServerStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(panelServerConfigLayout.createSequentialGroup()
                .addComponent(lblServerIcon)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelServerConfig1.setBackground(new java.awt.Color(0, 0, 0));
        panelServerConfig1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Konfiguracija baze podataka", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        lblDbUrl.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        lblDbUrl.setForeground(new java.awt.Color(255, 255, 255));
        lblDbUrl.setText("url:");

        lblUser.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("user:");

        lblPassword.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("password:");

        txtUrlDatabase.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        txtUrlDatabase.setDisabledTextColor(new java.awt.Color(102, 102, 102));

        txtUserDatabase.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        txtUserDatabase.setDisabledTextColor(new java.awt.Color(102, 102, 102));

        txtPasswordDB.setDisabledTextColor(new java.awt.Color(102, 102, 102));

        lblDBIcon.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        lblDBIcon.setForeground(new java.awt.Color(255, 255, 255));
        lblDBIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/ac/bg/fon/ps/images/dataBASEIcon.png"))); // NOI18N

        javax.swing.GroupLayout panelServerConfig1Layout = new javax.swing.GroupLayout(panelServerConfig1);
        panelServerConfig1.setLayout(panelServerConfig1Layout);
        panelServerConfig1Layout.setHorizontalGroup(
            panelServerConfig1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelServerConfig1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelServerConfig1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUser)
                    .addComponent(lblDbUrl)
                    .addComponent(lblPassword))
                .addGap(48, 48, 48)
                .addGroup(panelServerConfig1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUrlDatabase, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(txtUserDatabase, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(txtPasswordDB))
                .addGap(57, 57, 57)
                .addComponent(lblDBIcon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelServerConfig1Layout.setVerticalGroup(
            panelServerConfig1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelServerConfig1Layout.createSequentialGroup()
                .addGroup(panelServerConfig1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelServerConfig1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelServerConfig1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDbUrl)
                            .addComponent(txtUrlDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelServerConfig1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUser)
                            .addComponent(txtUserDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelServerConfig1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblDBIcon)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelServerConfig1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPasswordDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnPokreniServer.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        btnPokreniServer.setText("Pokreni server");
        btnPokreniServer.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnZaustaviServer.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        btnZaustaviServer.setText("Zaustavi server");
        btnZaustaviServer.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblError.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelServerConfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelServerConfig1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addComponent(btnPokreniServer, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnZaustaviServer, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addComponent(lblError)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addComponent(panelServerConfig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelServerConfig1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(lblError)
                .addGap(12, 12, 12)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPokreniServer, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZaustaviServer, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 27, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N

        menuKlijent.setBorder(null);
        menuKlijent.setText("Klijent");
        menuKlijent.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N

        miUpravljanje.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        miUpravljanje.setText("Upravljanje");
        miUpravljanje.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        miUpravljanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUpravljanjeActionPerformed(evt);
            }
        });
        menuKlijent.add(miUpravljanje);

        jMenuBar1.add(menuKlijent);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miUpravljanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUpravljanjeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miUpravljanjeActionPerformed

    public void pokreniServerBtnAddActionListener(ActionListener al){
        btnPokreniServer.addActionListener(al);
    }
    
    public void zaustaviServerBtnAddActionListener(ActionListener al){
        btnZaustaviServer.addActionListener(al);
    }
    
    public void miKorisniciManagementAddActionListener(ActionListener al){
        miUpravljanje.addActionListener(al);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPokreniServer;
    private javax.swing.JButton btnZaustaviServer;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblDBIcon;
    private javax.swing.JLabel lblDbUrl;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPort;
    private javax.swing.JLabel lblPort1;
    private javax.swing.JLabel lblServerIcon;
    private javax.swing.JLabel lblUser;
    private javax.swing.JMenu menuKlijent;
    private javax.swing.JMenuItem miUpravljanje;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelServerConfig;
    private javax.swing.JPanel panelServerConfig1;
    private javax.swing.JPasswordField txtPasswordDB;
    private javax.swing.JTextField txtPortServer;
    private javax.swing.JTextField txtServerStatus;
    private javax.swing.JTextField txtUrlDatabase;
    private javax.swing.JTextField txtUserDatabase;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnPokreniServer() {
        return btnPokreniServer;
    }
    
    public void setBtnPokreniServer(javax.swing.JButton btnPokreniServer) {
        this.btnPokreniServer = btnPokreniServer;
    }

    public javax.swing.JButton getBtnZaustaviServer() {
        return btnZaustaviServer;
    }

    public void setBtnZaustaviServer(javax.swing.JButton btnZaustaviServer) {
        this.btnZaustaviServer = btnZaustaviServer;
    }

    public javax.swing.JLabel getLblError() {
        return lblError;
    }

    public void setLblError(javax.swing.JLabel lblError) {
        this.lblError = lblError;
    }

    public javax.swing.JTextField getTxtPasswordDB() {
        return txtPasswordDB;
    }
    
    public javax.swing.JTextField getTxtPortServer() {
        return txtPortServer;
    }

    public void setTxtPortServer(javax.swing.JTextField txtPortServer) {
        this.txtPortServer = txtPortServer;
    }

    public javax.swing.JTextField getTxtServerStatus() {
        return txtServerStatus;
    }

    public void setTxtServerStatus(javax.swing.JTextField txtServerStatus) {
        this.txtServerStatus = txtServerStatus;
    }

    public javax.swing.JTextField getTxtUrlDatabase() {
        return txtUrlDatabase;
    }

    public void setTxtUrlDatabase(javax.swing.JTextField txtUrlDatabase) {
        this.txtUrlDatabase = txtUrlDatabase;
    }

    public javax.swing.JTextField getTxtUserDatabase() {
        return txtUserDatabase;
    }

    public void setTxtUserDatabase(javax.swing.JTextField txtUserDatabase) {
        this.txtUserDatabase = txtUserDatabase;
    }

    public javax.swing.JMenuItem getMiUpravljanje() {
        return miUpravljanje;
    }

    public void setMiUpravljanje(javax.swing.JMenuItem miUpravljanje) {
        this.miUpravljanje = miUpravljanje;
    }
    
}
